In [2]:
import pandas as pd
import numpy as np
import csv
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)
np.set_printoptions(threshold=np.inf)
pd.set_option('display.max_seq_items', None)

# 📥 Imports

In [3]:
books_small = pd.read_json('goodreads_books.json', lines=True, nrows=10000)
reviews_small = pd.read_json('goodreads_reviews_dedup.json', lines=True, nrows=1000)
authors = pd.read_json('goodreads_book_authors.json', lines=True, nrows=1000)
book_genres_small = pd.read_json('goodreads_book_genres_initial.json', lines=True, nrows=1000)
book_works_small = pd.read_json('goodreads_book_works.json', lines=True, nrows=1000)

In [4]:
# not intreseting
# book_clubs_small = pd.read_json('book_clubs.json', lines=True, nrows=100)
# book_series_small = pd.read_json('goodreads_book_series.json', lines=True, nrows=100)

## 📖 Books

In [5]:
books_small.sample(3)

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,similar_books,description,format,link,authors,publisher,num_pages,publication_day,isbn13,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
932,,2,[],US,ara,"[{'count': '10', 'name': 'to-read'}, {'count':...",,false,4.27,,[],,,https://www.goodreads.com/book/show/33293455,"[{'author_id': '16171754', 'role': ''}]",,,,,,,,https://www.goodreads.com/book/show/33293455,https://images.gr-assets.com/books/1481229016m...,33293455,11,54023770,اخلاقيات الاختلاف,اخلاقيات الاختلاف
608,1869415361,4,[],US,eng,"[{'count': '16', 'name': 'to-read'}, {'count':...",,false,3.00,B00BSGZFXC,[],Mark Inglis was working and climbing on Mt Coo...,,https://www.goodreads.com/book/show/5280606-no...,"[{'author_id': '776431', 'role': ''}]",,,,9781869415365,,,,https://www.goodreads.com/book/show/5280606-no...,https://images.gr-assets.com/books/1304505536m...,5280606,18,5348007,No mean feat,No mean feat
392,,15,[460829],US,en-US,"[{'count': '2448', 'name': 'to-read'}, {'count...",B00AR2RZ4K,true,3.83,B00AR2RZ4K,"[18775227, 13352266, 17793578, 13538762, 18190...",The year is AD 7000. The human species is exti...,,https://www.goodreads.com/book/show/18663975-n...,"[{'author_id': '8794', 'role': ''}]",,,,,,,,https://www.goodreads.com/book/show/18663975-n...,https://s.gr-assets.com/assets/nophoto/book/11...,18663975,699,21562011,Neptune's Brood,Neptune's Brood

In [24]:
books_small['language_code'].value_counts()

language_code
         4457
eng      3050
en-US     402
spa       235
ita       221
en-GB     218
ara       156
fre       126
ger       124
por       121
ind       115
nl         77
tur        66
per        54
fin        52
en-CA      41
cze        39
gre        37
swe        37
jpn        37
pol        26
rum        25
dan        23
rus        21
msa        21
bul        20
ben        16
nor        16
vie        15
slo        15
tha        14
hun        13
lav         9
est         9
lit         8
zho         8
ukr         7
scr         6
cat         5
srp         5
nob         5
kat         4
pes         4
tam         4
slv         3
kor         3
heb         3
afr         3
mar         2
urd         2
nno         2
fil         2
en          2
grc         1
mul         1
hin         1
mkd         1
--          1
mus         1
mon         1
hye         1
nep         1
guj         1
sqi         1
bos         1
enm         1
gla         1
Name: count, dtype: int64

In [47]:
books_small[books_small['language_code']=='fre']
books_small[books_small['language_code'].str.startswith('en', na=False)]
books_small[books_small['language_code']=='nl']
# books_small[books_small['book_id']==3947021]

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,similar_books,description,format,link,authors,publisher,num_pages,publication_day,isbn13,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
216,9025440541,7,[],US,nl,"[{'count': '308', 'name': 'to-read'}, {'count'...",,false,3.45,,"[32981685, 1906041, 326023, 738448, 15735868, ...",Twee vrienden stappen de deur uit om in de dic...,Paperback,https://www.goodreads.com/book/show/16174656-d...,"[{'author_id': '3354', 'role': ''}, {'author_i...",Atlas Contact,80,,9789025440541,11,,2012,https://www.goodreads.com/book/show/16174656-d...,https://images.gr-assets.com/books/1354030481m...,16174656,126,25630364,De broodjesroofverhalen,De broodjesroofverhalen
656,,2,[],US,nl,"[{'count': '6', 'name': 'to-read'}, {'count': ...",,false,4.17,,[],Tori vertelt het bloedstollende avontuur van d...,Hardcover,https://www.goodreads.com/book/show/36340366-tori,"[{'author_id': '17200611', 'role': ''}, {'auth...",Das Mag,129,,9789492478504,9,,2017,https://www.goodreads.com/book/show/36340366-tori,https://images.gr-assets.com/books/1506942096m...,36340366,6,58020338,Tori,Tori
683,,2,[],US,nl,"[{'count': '11', 'name': 'to-read'}, {'count':...",,true,2.50,,[],Op 27 oktober 1961 vindt een metselaar in de t...,ebook,https://www.goodreads.com/book/show/16010560-m...,"[{'author_id': '2779162', 'role': ''}]",Bruna,133,,9789044960853,9,,2006,https://www.goodreads.com/book/show/16010560-m...,https://images.gr-assets.com/books/1352061374m...,16010560,4,21777785,Mysteries in Utrecht,Mysteries in Utrecht
737,9026338570,2,[],US,nl,"[{'count': '480', 'name': 'to-read'}, {'count'...",,false,3.06,,[],"Als Robert Walter, geliefd burgemeester van Am...",Audiobook,https://www.goodreads.com/book/show/32860452-d...,"[{'author_id': '1245772', 'role': ''}, {'autho...",Ambo Anthos,9,27,9789026338571,10,,2016,https://www.goodreads.com/book/show/32860452-d...,https://images.gr-assets.com/books/1478117312m...,32860452,6,52055275,De greppel,De greppel
749,9024531101,1,[],US,nl,"[{'count': '1197', 'name': 'to-read'}, {'count...",,false,3.76,,"[406422, 2976991, 365016, 819789, 7443273, 963...","Ze noemen hem Beul, een seriemoordenaar die al...",Paperback,https://www.goodreads.com/book/show/12388485-d...,"[{'author_id': '1441', 'role': ''}, {'author_i...",Luitingh,,,9789024531103,1,,2010,https://www.goodreads.com/book/show/12388485-d...,https://images.gr-assets.com/books/1330427741m...,12388485,10,6179606,De dochters van de beul,De dochters van de beul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9595,9059651790,15,[],US,nl,"[{'count': '2335', 'name': 'to-read'}, {'count...",,false,3.82,,"[418677, 2947312, 1380834, 3392412, 1696465, 6...",An alternate cover for this isbn can be found ...,Paperback,https://www.goodreads.com/book/show/16122383-d...,"[{'author_id': '184683', 'role': ''}]",Stichting Collectieve Propaganda van het Neder...,319,1,9789059651791,11,Nederland Leest,2012,https://www.goodreads.com/book/show/16122383-d...,https://images.gr-assets.com/books/1351790917m...,16122383,139,2319357,De donkere kamer van Damokles,De donkere kamer van Damokles
9654,,1,[],US,nl,"[{'count': '4', 'name': 'to-read'}, {'count': ...",,false,3.33,,[],Dat het leven wonderlijk is en heel vaak reken...,Hardcover,https://www.goodreads.com/book/show/12825600-h...,"[{'author_id': '540261', 'role': ''}]",West-Friesland,204,,,,,1956,https://www.goodreads.com/book/show/12825600-h...,https://images.gr-assets.com/books/1318082042m...,12825600,12,17975475,Het leven is een wonder,Het leven is een wonder
9796,,4,[],US,nl,"[{'count': '2175', 'name': 'to-read'}, {'count...",,false,4.15,,"[177047, 70883, 263914, 323170, 7865039, 2155236]","Henry Molise, vijftig jaar oud en succesvol sc...",Hardcover,https://www.goodreads.com/book/show/22874981-d...,"[{'author_id': '25864', 'role': ''}, {'author_...",Meulenhoff,216,23,9789029089661,5,,2014,https://www.goodreads.com/book/show/22874981-d...,https://images.gr-assets.com/books/1407240786m...,22874981,18,87110,De broederschap van de druif,De broederschap van de druif
9933,,1,[],US,nl,"[{'count': '3', 'name': 'to-read'}, {'count': ...",9789035143,false,3.17,,[],Op de Nieuwe Maas waait je altijd een frisse b...,Paperback,https://www.goodreads.com/book/show/34655855-r...,"[{'author_id': '399482', 'role': ''}]",Prometheus/Bert Bakker,272,12,,3,,2017,https://www.goodreads.com/book/show/34655855-r...,https://images.gr-assets.com/books/1490099794m...,34655855,6,55818612,Rotterdam bruid van de maas - Van prehistorie ...,Rotterdam bruid van de maas - Van prehistorie ...
9952,9029567732,18,[],US,nl,"[{'count': '125', 'name': 'to-read'}, {'count'...",,false,3.37,,"[9499588, 17566164, 8904169, 6696797, 1160575,...",'Dit is niet enkel mijn verhaal. Dit is het ve...,Paperback,https://www.goodreads.com/book/show/9209656-ho...,"[{'author_id': '4146856', 'role': ''}]",De Arbeiderspers,207,,9789029567732,10,,2009,https://www.goodreads.com/book/show/9209656-ho...,https://s.gr-assets.com/assets/nophoto/book/11...,9209656,225,14089337,Hoe de wereld perfect functioneert zonder mij,Hoe de wereld perfect functioneert zonder mij

In [ ]:
import os
import pandas as pd

json_file = "goodreads_books.json"

fra_file = "FRA.csv"
eng_file = "ENG.csv"
dut_file = "DUT.csv"

chunksize = 10000

for file in [fra_file, eng_file, dut_file]:
    if os.path.exists(file):
        os.remove(file)

for i, chunk in enumerate(pd.read_json(json_file, lines=True, chunksize=chunksize)):
    print(f"Processing chunk {i + 1}...")

    chunk["language_code_str"] = chunk["language_code"].fillna("").astype(str)

    fra_chunk = chunk[chunk["language_code_str"] == "fre"].drop(columns=["language_code_str"])
    eng_chunk = chunk[chunk["language_code_str"].str.startswith("en")].drop(columns=["language_code_str"])
    dut_chunk = chunk[chunk["language_code_str"] == "nl"].drop(columns=["language_code_str"])

    if not fra_chunk.empty:
        fra_chunk.to_csv(
            fra_file,
            mode="a",
            index=False,
            header=not os.path.exists(fra_file)
        )

    if not eng_chunk.empty:
        eng_chunk.to_csv(
            eng_file,
            mode="a",
            index=False,
            header=not os.path.exists(eng_file)
        )

    if not dut_chunk.empty:
        dut_chunk.to_csv(
            dut_file,
            mode="a",
            index=False,
            header=not os.path.exists(dut_file)
        )

print("Done.")

## 📝 Reviews

In [6]:
reviews_small.sample(3)

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
934,01ec1a320ffded6b2dd47833f2c8e4fb,20922567,a48d7714c50965ec77dad047b24ab4d1,4,"I loved this story! First of all, although it'...",Sat Jun 14 16:32:54 -0700 2014,Sat Oct 18 08:34:06 -0700 2014,,,3,0
826,01ec1a320ffded6b2dd47833f2c8e4fb,22057891,6c7a45accb94edba534249907227b0f2,4,4 - 4.5 stars!! \n A story about hopes and dre...,Wed Nov 12 19:10:39 -0800 2014,Thu Feb 05 16:42:43 -0800 2015,Thu Feb 05 00:00:00 -0800 2015,Tue Feb 03 00:00:00 -0800 2015,8,0
308,ab2923b738ea3082f5f3efcbbfacb218,2187,8e3d0aa72c1d74216e5ff5ad7b8c2bbe,5,Overall I really loved this book. The writing ...,Sat Jul 19 08:05:52 -0700 2014,Tue Aug 12 06:38:25 -0700 2014,Mon Aug 11 00:00:00 -0700 2014,Sat Jul 19 00:00:00 -0700 2014,0,0

## ✍️ Authors

In [7]:
authors.sample(3)

,average_rating,author_id,text_reviews_count,name,ratings_count
704,3.67,15016585,1,Tarik Alemdar,3
396,3.63,5372204,540,Tamara Morgan,2087
566,4.07,4722094,3211,Jonathan Auxier,18645

## 🎭 Genres

In [8]:
book_genres_small.sample(3)

      book_id              genres
680  23437668  {'non-fiction': 1}
140  23566090                  {}
296  30330413      {'fiction': 1}

## 🧩 Works

In [9]:
book_works_small.sample(3)

,books_count,reviews_count,original_publication_month,default_description_language_code,text_reviews_count,best_book_id,original_publication_year,original_title,rating_dist,default_chaptering_book_id,original_publication_day,original_language_id,ratings_count,media_type,ratings_sum,work_id
372,3,280,,,18,117707,1997,I Was Wrong: The Untold Story of the Shocking ...,5:40|4:47|3:34|2:9|1:4|total:134,,,,134,book,512,113316
233,4,206,9,,11,12752275,2011,,5:18|4:10|3:4|2:0|1:1|total:33,,1,,33,book,143,17893172
504,1008,173508,2,,3037,30474,1848,Manifest der Kommunistischen Partei,5:16051|4:21283|3:22925|2:8665|1:3695|total:72619,,,,72619,book,255187,2205479

In [6]:
book_small = pd.read_json('goodreads_books.json', lines=True, nrows=10000)

In [166]:
book_small = pd.read_json('goodreads_books.json', lines=True, nrows=10000)

In [5]:
book_small.columns

Index(['isbn', 'text_reviews_count', 'series', 'country_code', 'language_code',
       'popular_shelves', 'asin', 'is_ebook', 'average_rating', 'kindle_asin',
       'similar_books', 'description', 'format', 'link', 'authors',
       'publisher', 'num_pages', 'publication_day', 'isbn13',
       'publication_month', 'edition_information', 'publication_year', 'url',
       'image_url', 'book_id', 'ratings_count', 'work_id', 'title',
       'title_without_series'],
      dtype='object')

In [219]:
reviews_small.columns

Index(['user_id', 'book_id', 'review_id', 'rating', 'review_text',
       'date_added', 'date_updated', 'read_at', 'started_at', 'n_votes',
       'n_comments'],
      dtype='object')

In [168]:
reviews_small[['user_id', 'book_id', 'review_id', 'rating', 'review_text',
       'date_added', 'date_updated', 'read_at', 'started_at', 'n_votes',
       'n_comments']]

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,24375664,5cd416f3efc3f944fce4ce2db2290d5e,5,Mind blowingly cool. Best science fiction I've...,Fri Aug 25 13:55:02 -0700 2017,Mon Oct 09 08:55:59 -0700 2017,Sat Oct 07 00:00:00 -0700 2017,Sat Aug 26 00:00:00 -0700 2017,16,0
1,8842281e1d1347389f2ab93d60773d4d,18245960,dfdbb7b0eb5a7e4c26d59a937e2e5feb,5,This is a special book. It started slow for ab...,Sun Jul 30 07:44:10 -0700 2017,Wed Aug 30 00:00:26 -0700 2017,Sat Aug 26 12:05:52 -0700 2017,Tue Aug 15 13:23:18 -0700 2017,28,1
2,8842281e1d1347389f2ab93d60773d4d,6392944,5e212a62bced17b4dbe41150e5bb9037,3,I haven't read a fun mystery book in a while a...,Mon Jul 24 02:48:17 -0700 2017,Sun Jul 30 09:28:03 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,Mon Jul 24 00:00:00 -0700 2017,6,0
3,8842281e1d1347389f2ab93d60773d4d,22078596,fdd13cad0695656be99828cd75d6eb73,4,"Fun, fast paced, and disturbing tale of murder...",Mon Jul 24 02:33:09 -0700 2017,Sun Jul 30 10:23:54 -0700 2017,Sun Jul 30 15:42:05 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,22,4
4,8842281e1d1347389f2ab93d60773d4d,6644782,bd0df91c9d918c0e433b9ab3a9a5c451,4,A fun book that gives you a sense of living in...,Mon Jul 24 02:28:14 -0700 2017,Thu Aug 24 00:07:20 -0700 2017,Sat Aug 05 00:00:00 -0700 2017,Sun Jul 30 00:00:00 -0700 2017,8,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,5f550cc8d90df1759eda1496621187d8,4894,9e2986ed5f661870cf9e2b28c15a5a59,1,A good corporate companion piece to McCarthy's...,Wed Mar 19 01:33:50 -0700 2014,Thu Jan 26 22:28:56 -0800 2017,Fri Aug 01 00:00:00 -0700 2008,,0,2
9996,5f550cc8d90df1759eda1496621187d8,285500,d02154ffa968b9aed8545d8411d0fec3,5,"It still works, but like an 18th century steam...",Wed Mar 19 01:29:31 -0700 2014,Thu Jan 26 22:24:09 -0800 2017,Wed Sep 01 00:00:00 -0700 1993,,0,0
9997,5f550cc8d90df1759eda1496621187d8,7784,1042c7896d71be7271e1b9b411417001,5,Devastating. I was surprised to read that when...,Wed Mar 19 01:29:06 -0700 2014,Tue Aug 23 22:44:22 -0700 2016,,,1,0
9998,5f550cc8d90df1759eda1496621187d8,233093,7600ad6e89c32c543d9f316969ef711d,4,It was no time to play. It was no time for fun...,Wed Mar 19 01:26:44 -0700 2014,Mon Sep 29 23:28:09 -0700 2014,,,2,0
9999,5f550cc8d90df1759eda1496621187d8,23772,59ebc175f15623d694418969657ecb7b,2,The lesson here is that you cannot know whethe...,Wed Mar 19 01:26:02 -0700 2014,Wed Jul 02 00:13:14 -0700 2014,,,1,0

In [169]:
book_small[book_small.index==5338]

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,...,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
5338,8401354803,83,[566212],US,spa,"[{'count': '9125', 'name': 'to-read'}, {'count...",,false,4.10,,...,11,,2013,https://www.goodreads.com/book/show/18359794-d...,https://images.gr-assets.com/books/1376955133m...,18359794,426,17851499,"Doctor sueño (El resplandor, #2)","Doctor sueño (El resplandor, #2)"

In [170]:
book_genres_small.sort_values(by='book_id')

       book_id                                             genres
9818      2701  {'poetry': 1657, 'fiction': 612, 'history, his...
2009      4241  {'fiction': 11, 'non-fiction': 7, 'fantasy, pa...
8955      5335  {'fiction': 5152, 'fantasy, paranormal': 1285,...
8957      5337  {'fiction': 693, 'history, historical fiction,...
8960      5338  {'fantasy, paranormal': 45, 'poetry': 13, 'fic...
...        ...                                                ...
4452  36440733                                                 {}
9268  36441675                                                 {}
9263  36441679                                                 {}
326   36442770                                                 {}
1278  36451826  {'fiction': 157, 'fantasy, paranormal': 9, 'hi...

[10000 rows x 2 columns]

In [171]:
# book = book_small[['text_reviews_count', 'series', 'country_code',  'average_rating', 
#         'description', 'format', 
#         'num_pages' , 'publication_year', 
#        'image_url', 'book_id', 'ratings_count', 'work_id', 'title',
#        'title_without_series']]

# features= book[['text_reviews_count', 'series', 'country_code',  'average_rating', 
#          'format', 'num_pages' , 'publication_year', 'ratings_count']]
# feature_text = book[['description','title']]
# feature_img = book[['image_url']]
# feature_reviews = review[['rating', 'review_text', 'n_votes','n_comments']]

In [172]:
reviews_small = pd.read_json('goodreads_reviews_dedup.json', lines=True, nrows=10000)

In [173]:
reviews_small

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,24375664,5cd416f3efc3f944fce4ce2db2290d5e,5,Mind blowingly cool. Best science fiction I've...,Fri Aug 25 13:55:02 -0700 2017,Mon Oct 09 08:55:59 -0700 2017,Sat Oct 07 00:00:00 -0700 2017,Sat Aug 26 00:00:00 -0700 2017,16,0
1,8842281e1d1347389f2ab93d60773d4d,18245960,dfdbb7b0eb5a7e4c26d59a937e2e5feb,5,This is a special book. It started slow for ab...,Sun Jul 30 07:44:10 -0700 2017,Wed Aug 30 00:00:26 -0700 2017,Sat Aug 26 12:05:52 -0700 2017,Tue Aug 15 13:23:18 -0700 2017,28,1
2,8842281e1d1347389f2ab93d60773d4d,6392944,5e212a62bced17b4dbe41150e5bb9037,3,I haven't read a fun mystery book in a while a...,Mon Jul 24 02:48:17 -0700 2017,Sun Jul 30 09:28:03 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,Mon Jul 24 00:00:00 -0700 2017,6,0
3,8842281e1d1347389f2ab93d60773d4d,22078596,fdd13cad0695656be99828cd75d6eb73,4,"Fun, fast paced, and disturbing tale of murder...",Mon Jul 24 02:33:09 -0700 2017,Sun Jul 30 10:23:54 -0700 2017,Sun Jul 30 15:42:05 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,22,4
4,8842281e1d1347389f2ab93d60773d4d,6644782,bd0df91c9d918c0e433b9ab3a9a5c451,4,A fun book that gives you a sense of living in...,Mon Jul 24 02:28:14 -0700 2017,Thu Aug 24 00:07:20 -0700 2017,Sat Aug 05 00:00:00 -0700 2017,Sun Jul 30 00:00:00 -0700 2017,8,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,5f550cc8d90df1759eda1496621187d8,4894,9e2986ed5f661870cf9e2b28c15a5a59,1,A good corporate companion piece to McCarthy's...,Wed Mar 19 01:33:50 -0700 2014,Thu Jan 26 22:28:56 -0800 2017,Fri Aug 01 00:00:00 -0700 2008,,0,2
9996,5f550cc8d90df1759eda1496621187d8,285500,d02154ffa968b9aed8545d8411d0fec3,5,"It still works, but like an 18th century steam...",Wed Mar 19 01:29:31 -0700 2014,Thu Jan 26 22:24:09 -0800 2017,Wed Sep 01 00:00:00 -0700 1993,,0,0
9997,5f550cc8d90df1759eda1496621187d8,7784,1042c7896d71be7271e1b9b411417001,5,Devastating. I was surprised to read that when...,Wed Mar 19 01:29:06 -0700 2014,Tue Aug 23 22:44:22 -0700 2016,,,1,0
9998,5f550cc8d90df1759eda1496621187d8,233093,7600ad6e89c32c543d9f316969ef711d,4,It was no time to play. It was no time for fun...,Wed Mar 19 01:26:44 -0700 2014,Mon Sep 29 23:28:09 -0700 2014,,,2,0
9999,5f550cc8d90df1759eda1496621187d8,23772,59ebc175f15623d694418969657ecb7b,2,The lesson here is that you cannot know whethe...,Wed Mar 19 01:26:02 -0700 2014,Wed Jul 02 00:13:14 -0700 2014,,,1,0

In [174]:
# chunks = pd.read_json('goodreads_reviews_dedup.json', lines=True, chunksize=10000)

# dfs = []

# for chunk in chunks:
#     dfs.append(chunk[['book_id', 'rating', 'review_text']])

# reviews = pd.concat(dfs, ignore_index=True)

In [175]:
reviews_small[reviews_small.rating<3]['review_text'][9989]

"Some black man with a gun on campus and suddenly we all don't study Greek and Latin enough. The paranoid ramblings of a ... well, read Ravelstein."

# 🧪 review score vs emotion review text

In [200]:
import string
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_validate
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import recall_score
import unicodedata
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.model_selection import train_test_split, cross_validate

In [177]:
def preprocessing(sentence):

    lemmatizer = WordNetLemmatizer()

    # Basic cleaning
    sentence = sentence.strip()
    sentence = sentence.lower()
    sentence = ''.join(char for char in sentence if not char.isdigit())

    # Remove punctuation
    for punctuation in string.punctuation:
        sentence = sentence.replace(punctuation, '')

    # Tokenize
    tokenized_sentence = word_tokenize(sentence)

    # 1️⃣ Lemmatize verbs
    verb_lemmatized = [
        lemmatizer.lemmatize(word, pos="v")
        for word in tokenized_sentence
    ]

    # 2️⃣ Lemmatize nouns
    noun_lemmatized = [
        lemmatizer.lemmatize(word, pos="n")
        for word in verb_lemmatized
    ]

    # Join back
    cleaned_sentence = ' '.join(noun_lemmatized)

    return cleaned_sentence

In [178]:
data = reviews_small[['rating','review_text']].copy()
data['clean_reviews'] = data["review_text"].apply(preprocessing)
data

,rating,review_text,clean_reviews
0,5,Mind blowingly cool. Best science fiction I've...,mind blowingly cool best science fiction ive r...
1,5,This is a special book. It started slow for ab...,this be a special book it start slow for about...
2,3,I haven't read a fun mystery book in a while a...,i havent read a fun mystery book in a while an...
3,4,"Fun, fast paced, and disturbing tale of murder...",fun fast pace and disturb tale of murder great...
4,4,A fun book that gives you a sense of living in...,a fun book that give you a sense of live in pa...
...,...,...,...
9995,1,A good corporate companion piece to McCarthy's...,a good corporate companion piece to mccarthy t...
9996,5,"It still works, but like an 18th century steam...",it still work but like an th century steam eng...
9997,5,Devastating. I was surprised to read that when...,devastate i be surprise to read that when this...
9998,4,It was no time to play. It was no time for fun...,it be no time to play it be no time for fun wa...
9999,2,The lesson here is that you cannot know whethe...,the lesson here be that you can not know wheth...

In [211]:
data['target'] = (data['rating'] > 3).astype(int)
data['review_text'][9995]

"A good corporate companion piece to McCarthy's The Road, this little gem explains how life is like an endless maze and we must struggle every day in order to survive. Those who fail to survive, well, they have just given up, and deserve what they get. So don't give up, screams social Darwinist Herbert Spenser, screams the preacher man in The Poseidon Adventure, screams Yertle the Turtle as his tower of subservient turtles struggles to keep their balance under the weight of the self-centered creep."

In [212]:
count_vectorizer = CountVectorizer()
X = count_vectorizer.fit_transform(data['clean_reviews'])
X.toarray() # pour optimizé l'espace

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [213]:
display(count_vectorizer.get_feature_names_out())
X.shape

array(['aaaaah', 'aaand', 'aaasr', ..., 'zyz', 'zz', 'zzyl'], dtype=object)

(10000, 48994)

In [214]:
# Feature/Target
X = X
y = data['target']

# Pipeline vectorizer + Naive Bayes
model = MultinomialNB()

# Cross-validation
cv_results = cross_validate(model, X, y, cv = 5, scoring = ["accuracy"])
average_accuracy = cv_results["test_accuracy"].mean()
np.round(average_accuracy,2)

0.68

In [215]:
np.unique(y,return_counts=True)

(array([0, 1]), array([3345, 6655]))

In [216]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)
model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.744
0.6893333333333334

In [217]:
new_review = ["A good corporate companion piece to McCarthy's The Road, this little gem explains how life is like an endless maze and we must struggle every day in order to survive. Those who fail to survive, well, they have just given up, and deserve what they get. So don't give up, screams social Darwinist Herbert Spenser, screams the preacher man in The Poseidon Adventure, screams Yertle the Turtle as his tower of subservient turtles struggles to keep their balance under the weight of the self-centered creep."]

# Apply preprocessing manually
new_review_clean = [preprocessing(text) for text in new_review]

# Transform
new_review_vec = count_vectorizer.transform(new_review_clean)

# Predict
prediction = model.predict(new_review_vec)

print(prediction)

[0]

In [111]:
vectorizer = CountVectorizer(ngram_range = (2,2))
naivebayes = MultinomialNB()

X_bow = vectorizer.fit_transform(data.clean_reviews)

cv_nb = cross_validate(
    naivebayes,
    X_bow,
    data.target,
    scoring = "accuracy"
)

round(cv_nb['test_score'].mean(),2)

0.74

# 🌍 Make books files Fra,Dut,Eng

## books FRA,DUT,ENG

In [49]:
# json_file = "goodreads_books.json"

# fra_file = "FRA.csv"
# eng_file = "ENG.csv"
# dut_file = "DUT.csv"

# chunksize = 10000
# headers_written = False
# fra = 0
# eng = 0
# dut = 0

# with open(fra_file, "w", newline="", encoding="utf-8") as fra_f, \
#      open(eng_file, "w", newline="", encoding="utf-8") as eng_f, \
#      open(dut_file, "w", newline="", encoding="utf-8") as dut_f:

#     fra_writer = None
#     eng_writer = None
#     dut_writer = None

    

#     for i, chunk in enumerate(pd.read_json(json_file, lines=True, chunksize=chunksize)):
#         print(f"Processing chunk {i + 1}...")

#         for _, row in chunk.iterrows():
#             lang = row.get("language_code")

#             if pd.isna(lang):
#                 continue

#             lang = str(lang)
#             row_dict = row.to_dict()

#             if not headers_written:
#                 fieldnames = list(row_dict.keys())
#                 fra_writer = csv.DictWriter(fra_f, fieldnames=fieldnames)
#                 eng_writer = csv.DictWriter(eng_f, fieldnames=fieldnames)
#                 dut_writer = csv.DictWriter(dut_f, fieldnames=fieldnames)

#                 fra_writer.writeheader()
#                 eng_writer.writeheader()
#                 dut_writer.writeheader()

#                 headers_written = True

#             if lang == "fre":
#                 fra_writer.writerow(row_dict)
#                 fra = fra + 1
#             elif lang.startswith("en"):
#                 eng_writer.writerow(row_dict)
#                 eng = eng + 1
#             elif lang == "nl":
#                 dut_writer.writerow(row_dict)
#                 dut = dut + 1

# print("Done.")
# print(f"fra:{fra}")
# print(f"eng:{eng}")
# print(f"dut:{dut}")


# fra:32.046
# eng:866.183
# dut:17.497

Processing chunk 1...
Processing chunk 2...
Processing chunk 3...
Processing chunk 4...
Processing chunk 5...
Processing chunk 6...
Processing chunk 7...
Processing chunk 8...
Processing chunk 9...
Processing chunk 10...
Processing chunk 11...
Processing chunk 12...
Processing chunk 13...
Processing chunk 14...
Processing chunk 15...
Processing chunk 16...
Processing chunk 17...
Processing chunk 18...
Processing chunk 19...
Processing chunk 20...
Processing chunk 21...
Processing chunk 22...
Processing chunk 23...
Processing chunk 24...
Processing chunk 25...
Processing chunk 26...
Processing chunk 27...
Processing chunk 28...
Processing chunk 29...
Processing chunk 30...
Processing chunk 31...
Processing chunk 32...
Processing chunk 33...
Processing chunk 34...
Processing chunk 35...
Processing chunk 36...
Processing chunk 37...
Processing chunk 38...
Processing chunk 39...
Processing chunk 40...
Processing chunk 41...
Processing chunk 42...
Processing chunk 43...
Processing chunk 44...
Processing chunk 45...
Processing chunk 46...
Processing chunk 47...
Processing chunk 48...
Processing chunk 49...
Processing chunk 50...
Processing chunk 51...
Processing chunk 52...
Processing chunk 53...
Processing chunk 54...
Processing chunk 55...
Processing chunk 56...
Processing chunk 57...
Processing chunk 58...
Processing chunk 59...
Processing chunk 60...
Processing chunk 61...
Processing chunk 62...
Processing chunk 63...
Processing chunk 64...
Processing chunk 65...
Processing chunk 66...
Processing chunk 67...
Processing chunk 68...
Processing chunk 69...
Processing chunk 70...
Processing chunk 71...
Processing chunk 72...
Processing chunk 73...
Processing chunk 74...
Processing chunk 75...
Processing chunk 76...
Processing chunk 77...
Processing chunk 78...
Processing chunk 79...
Processing chunk 80...
Processing chunk 81...
Processing chunk 82...
Processing chunk 83...
Processing chunk 84...
Processing chunk 85...
Processing chunk 86...
Processing chunk 87...
Processing chunk 88...
Processing chunk 89...
Processing chunk 90...
Processing chunk 91...
Processing chunk 92...
Processing chunk 93...
Processing chunk 94...
Processing chunk 95...
Processing chunk 96...
Processing chunk 97...
Processing chunk 98...
Processing chunk 99...
Processing chunk 100...
Processing chunk 101...
Processing chunk 102...
Processing chunk 103...
Processing chunk 104...
Processing chunk 105...
Processing chunk 106...
Processing chunk 107...
Processing chunk 108...
Processing chunk 109...
Processing chunk 110...
Processing chunk 111...
Processing chunk 112...
Processing chunk 113...
Processing chunk 114...
Processing chunk 115...
Processing chunk 116...
Processing chunk 117...
Processing chunk 118...
Processing chunk 119...
Processing chunk 120...
Processing chunk 121...
Processing chunk 122...
Processing chunk 123...
Processing chunk 124...
Processing chunk 125...
Processing chunk 126...
Processing chunk 127...
Processing chunk 128...
Processing chunk 129...
Processing chunk 130...
Processing chunk 131...
Processing chunk 132...
Processing chunk 133...
Processing chunk 134...
Processing chunk 135...
Processing chunk 136...
Processing chunk 137...
Processing chunk 138...
Processing chunk 139...
Processing chunk 140...
Processing chunk 141...
Processing chunk 142...
Processing chunk 143...
Processing chunk 144...
Processing chunk 145...
Processing chunk 146...
Processing chunk 147...
Processing chunk 148...
Processing chunk 149...
Processing chunk 150...
Processing chunk 151...
Processing chunk 152...
Processing chunk 153...
Processing chunk 154...
Processing chunk 155...
Processing chunk 156...
Processing chunk 157...
Processing chunk 158...
Processing chunk 159...
Processing chunk 160...
Processing chunk 161...
Processing chunk 162...
Processing chunk 163...
Processing chunk 164...
Processing chunk 165...
Processing chunk 166...
Processing chunk 167...
Processing chunk 168...
Processing chunk 169...
Processing chunk 170...
Processing chunk 171...
Processing chunk 172...
Processing chunk 173...
Processing chunk 174...
Processing chunk 175...
Processing chunk 176...
Processing chunk 177...
Processing chunk 178...
Processing chunk 179...
Processing chunk 180...
Processing chunk 181...
Processing chunk 182...
Processing chunk 183...
Processing chunk 184...
Processing chunk 185...
Processing chunk 186...
Processing chunk 187...
Processing chunk 188...
Processing chunk 189...
Processing chunk 190...
Processing chunk 191...
Processing chunk 192...
Processing chunk 193...
Processing chunk 194...
Processing chunk 195...
Processing chunk 196...
Processing chunk 197...
Processing chunk 198...
Processing chunk 199...
Processing chunk 200...
Processing chunk 201...
Processing chunk 202...
Processing chunk 203...
Processing chunk 204...
Processing chunk 205...
Processing chunk 206...
Processing chunk 207...
Processing chunk 208...
Processing chunk 209...
Processing chunk 210...
Processing chunk 211...
Processing chunk 212...
Processing chunk 213...
Processing chunk 214...
Processing chunk 215...
Processing chunk 216...
Processing chunk 217...
Processing chunk 218...
Processing chunk 219...
Processing chunk 220...
Processing chunk 221...
Processing chunk 222...
Processing chunk 223...
Processing chunk 224...
Processing chunk 225...
Processing chunk 226...
Processing chunk 227...
Processing chunk 228...
Processing chunk 229...
Processing chunk 230...
Processing chunk 231...
Processing chunk 232...
Processing chunk 233...
Processing chunk 234...
Processing chunk 235...
Processing chunk 236...
Processing chunk 237...
Done.
fra:32046
eng:866183
dut:17497

## Reviews FRA

In [57]:
# books_fra = pd.read_csv('FRA.csv')
# book_ids = set(books_fra['book_id'])

# json_file = "goodreads_reviews_dedup.json"
# output_file = "reviews_FRA.csv"

# chunksize = 10000
# header_written = False
# reviews_fra = 0

# with open(output_file, "w", newline="", encoding="utf-8") as f:
#     writer = None

#     for i, chunk in enumerate(pd.read_json(json_file, lines=True, chunksize=chunksize)):
#         print(f"Processing chunk {i+1}...")

#         for _, row in chunk.iterrows():
#             if row['book_id'] in book_ids:
#                 reviews_fra = reviews_fra + 1
#                 row_dict = row.to_dict()

#                 # Initialize writer once with headers
#                 if not header_written:
#                     writer = csv.DictWriter(f, fieldnames=row_dict.keys())
#                     writer.writeheader()
#                     header_written = True

#                 # Write ONE row immediately
#                 writer.writerow(row_dict)

# print("Done.")
# print(f"FRA reviews count:{reviews_fra}")

# FRA reviews count:59.155

Processing chunk 1...
Processing chunk 2...
Processing chunk 3...
Processing chunk 4...
Processing chunk 5...
Processing chunk 6...
Processing chunk 7...
Processing chunk 8...
Processing chunk 9...
Processing chunk 10...
Processing chunk 11...
Processing chunk 12...
Processing chunk 13...
Processing chunk 14...
Processing chunk 15...
Processing chunk 16...
Processing chunk 17...
Processing chunk 18...
Processing chunk 19...
Processing chunk 20...
Processing chunk 21...
Processing chunk 22...
Processing chunk 23...
Processing chunk 24...
Processing chunk 25...
Processing chunk 26...
Processing chunk 27...
Processing chunk 28...
Processing chunk 29...
Processing chunk 30...
Processing chunk 31...
Processing chunk 32...
Processing chunk 33...
Processing chunk 34...
Processing chunk 35...
Processing chunk 36...
Processing chunk 37...
Processing chunk 38...
Processing chunk 39...
Processing chunk 40...
Processing chunk 41...
Processing chunk 42...
Processing chunk 43...
Processing chunk 44...
Processing chunk 45...
Processing chunk 46...
Processing chunk 47...
Processing chunk 48...
Processing chunk 49...
Processing chunk 50...
Processing chunk 51...
Processing chunk 52...
Processing chunk 53...
Processing chunk 54...
Processing chunk 55...
Processing chunk 56...
Processing chunk 57...
Processing chunk 58...
Processing chunk 59...
Processing chunk 60...
Processing chunk 61...
Processing chunk 62...
Processing chunk 63...
Processing chunk 64...
Processing chunk 65...
Processing chunk 66...
Processing chunk 67...
Processing chunk 68...
Processing chunk 69...
Processing chunk 70...
Processing chunk 71...
Processing chunk 72...
Processing chunk 73...
Processing chunk 74...
Processing chunk 75...
Processing chunk 76...
Processing chunk 77...
Processing chunk 78...
Processing chunk 79...
Processing chunk 80...
Processing chunk 81...
Processing chunk 82...
Processing chunk 83...
Processing chunk 84...
Processing chunk 85...
Processing chunk 86...
Processing chunk 87...
Processing chunk 88...
Processing chunk 89...
Processing chunk 90...
Processing chunk 91...
Processing chunk 92...
Processing chunk 93...
Processing chunk 94...
Processing chunk 95...
Processing chunk 96...
Processing chunk 97...
Processing chunk 98...
Processing chunk 99...
Processing chunk 100...
Processing chunk 101...
Processing chunk 102...
Processing chunk 103...
Processing chunk 104...
Processing chunk 105...
Processing chunk 106...
Processing chunk 107...
Processing chunk 108...
Processing chunk 109...
Processing chunk 110...
Processing chunk 111...
Processing chunk 112...
Processing chunk 113...
Processing chunk 114...
Processing chunk 115...
Processing chunk 116...
Processing chunk 117...
Processing chunk 118...
Processing chunk 119...
Processing chunk 120...
Processing chunk 121...
Processing chunk 122...
Processing chunk 123...
Processing chunk 124...
Processing chunk 125...
Processing chunk 126...
Processing chunk 127...
Processing chunk 128...
Processing chunk 129...
Processing chunk 130...
Processing chunk 131...
Processing chunk 132...
Processing chunk 133...
Processing chunk 134...
Processing chunk 135...
Processing chunk 136...
Processing chunk 137...
Processing chunk 138...
Processing chunk 139...
Processing chunk 140...
Processing chunk 141...
Processing chunk 142...
Processing chunk 143...
Processing chunk 144...
Processing chunk 145...
Processing chunk 146...
Processing chunk 147...
Processing chunk 148...
Processing chunk 149...
Processing chunk 150...
Processing chunk 151...
Processing chunk 152...
Processing chunk 153...
Processing chunk 154...
Processing chunk 155...
Processing chunk 156...
Processing chunk 157...
Processing chunk 158...
Processing chunk 159...
Processing chunk 160...
Processing chunk 161...
Processing chunk 162...
Processing chunk 163...
Processing chunk 164...
Processing chunk 165...
Processing chunk 166...
Processing chunk 167...
Processing chunk 168...
Processing chunk 169...
Processing chunk 170...
Processing chunk 171...
Processing chunk 172...
Processing chunk 173...
Processing chunk 174...
Processing chunk 175...
Processing chunk 176...
Processing chunk 177...
Processing chunk 178...
Processing chunk 179...
Processing chunk 180...
Processing chunk 181...
Processing chunk 182...
Processing chunk 183...
Processing chunk 184...
Processing chunk 185...
Processing chunk 186...
Processing chunk 187...
Processing chunk 188...
Processing chunk 189...
Processing chunk 190...
Processing chunk 191...
Processing chunk 192...
Processing chunk 193...
Processing chunk 194...
Processing chunk 195...
Processing chunk 196...
Processing chunk 197...
Processing chunk 198...
Processing chunk 199...
Processing chunk 200...
Processing chunk 201...
Processing chunk 202...
Processing chunk 203...
Processing chunk 204...
Processing chunk 205...
Processing chunk 206...
Processing chunk 207...
Processing chunk 208...
Processing chunk 209...
Processing chunk 210...
Processing chunk 211...
Processing chunk 212...
Processing chunk 213...
Processing chunk 214...
Processing chunk 215...
Processing chunk 216...
Processing chunk 217...
Processing chunk 218...
Processing chunk 219...
Processing chunk 220...
Processing chunk 221...
Processing chunk 222...
Processing chunk 223...
Processing chunk 224...
Processing chunk 225...
Processing chunk 226...
Processing chunk 227...
Processing chunk 228...
Processing chunk 229...
Processing chunk 230...
Processing chunk 231...
Processing chunk 232...
Processing chunk 233...
Processing chunk 234...
Processing chunk 235...
Processing chunk 236...
Processing chunk 237...
Processing chunk 238...
Processing chunk 239...
Processing chunk 240...
Processing chunk 241...
Processing chunk 242...
Processing chunk 243...
Processing chunk 244...
Processing chunk 245...
Processing chunk 246...
Processing chunk 247...
Processing chunk 248...
Processing chunk 249...
Processing chunk 250...
Processing chunk 251...
Processing chunk 252...
Processing chunk 253...
Processing chunk 254...
Processing chunk 255...
Processing chunk 256...
Processing chunk 257...
Processing chunk 258...
Processing chunk 259...
Processing chunk 260...
Processing chunk 261...
Processing chunk 262...
Processing chunk 263...
Processing chunk 264...
Processing chunk 265...
Processing chunk 266...
Processing chunk 267...
Processing chunk 268...
Processing chunk 269...
Processing chunk 270...
Processing chunk 271...
Processing chunk 272...
Processing chunk 273...
Processing chunk 274...
Processing chunk 275...
Processing chunk 276...
Processing chunk 277...
Processing chunk 278...
Processing chunk 279...
Processing chunk 280...
Processing chunk 281...
Processing chunk 282...
Processing chunk 283...
Processing chunk 284...
Processing chunk 285...
Processing chunk 286...
Processing chunk 287...
Processing chunk 288...
Processing chunk 289...
Processing chunk 290...
Processing chunk 291...
Processing chunk 292...
Processing chunk 293...
Processing chunk 294...
Processing chunk 295...
Processing chunk 296...
Processing chunk 297...
Processing chunk 298...
Processing chunk 299...
Processing chunk 300...
Processing chunk 301...
Processing chunk 302...
Processing chunk 303...
Processing chunk 304...
Processing chunk 305...
Processing chunk 306...
Processing chunk 307...
Processing chunk 308...
Processing chunk 309...
Processing chunk 310...
Processing chunk 311...
Processing chunk 312...
Processing chunk 313...
Processing chunk 314...
Processing chunk 315...
Processing chunk 316...
Processing chunk 317...
Processing chunk 318...
Processing chunk 319...
Processing chunk 320...
Processing chunk 321...
Processing chunk 322...
Processing chunk 323...
Processing chunk 324...
Processing chunk 325...
Processing chunk 326...
Processing chunk 327...
Processing chunk 328...
Processing chunk 329...
Processing chunk 330...
Processing chunk 331...
Processing chunk 332...
Processing chunk 333...
Processing chunk 334...
Processing chunk 335...
Processing chunk 336...
Processing chunk 337...
Processing chunk 338...
Processing chunk 339...
Processing chunk 340...
Processing chunk 341...
Processing chunk 342...
Processing chunk 343...
Processing chunk 344...
Processing chunk 345...
Processing chunk 346...
Processing chunk 347...
Processing chunk 348...
Processing chunk 349...
Processing chunk 350...
Processing chunk 351...
Processing chunk 352...
Processing chunk 353...
Processing chunk 354...
Processing chunk 355...
Processing chunk 356...
Processing chunk 357...
Processing chunk 358...
Processing chunk 359...
Processing chunk 360...
Processing chunk 361...
Processing chunk 362...
Processing chunk 363...
Processing chunk 364...
Processing chunk 365...
Processing chunk 366...
Processing chunk 367...
Processing chunk 368...
Processing chunk 369...
Processing chunk 370...
Processing chunk 371...
Processing chunk 372...
Processing chunk 373...
Processing chunk 374...
Processing chunk 375...
Processing chunk 376...
Processing chunk 377...
Processing chunk 378...
Processing chunk 379...
Processing chunk 380...
Processing chunk 381...
Processing chunk 382...
Processing chunk 383...
Processing chunk 384...
Processing chunk 385...
Processing chunk 386...
Processing chunk 387...
Processing chunk 388...
Processing chunk 389...
Processing chunk 390...
Processing chunk 391...
Processing chunk 392...
Processing chunk 393...
Processing chunk 394...
Processing chunk 395...
Processing chunk 396...
Processing chunk 397...
Processing chunk 398...
Processing chunk 399...
Processing chunk 400...
Processing chunk 401...
Processing chunk 402...
Processing chunk 403...
Processing chunk 404...
Processing chunk 405...
Processing chunk 406...
Processing chunk 407...
Processing chunk 408...
Processing chunk 409...
Processing chunk 410...
Processing chunk 411...
Processing chunk 412...
Processing chunk 413...
Processing chunk 414...
Processing chunk 415...
Processing chunk 416...
Processing chunk 417...
Processing chunk 418...
Processing chunk 419...
Processing chunk 420...
Processing chunk 421...
Processing chunk 422...
Processing chunk 423...
Processing chunk 424...
Processing chunk 425...
Processing chunk 426...
Processing chunk 427...
Processing chunk 428...
Processing chunk 429...
Processing chunk 430...
Processing chunk 431...
Processing chunk 432...
Processing chunk 433...
Processing chunk 434...
Processing chunk 435...
Processing chunk 436...
Processing chunk 437...
Processing chunk 438...
Processing chunk 439...
Processing chunk 440...
Processing chunk 441...
Processing chunk 442...
Processing chunk 443...
Processing chunk 444...
Processing chunk 445...
Processing chunk 446...
Processing chunk 447...
Processing chunk 448...
Processing chunk 449...
Processing chunk 450...
Processing chunk 451...
Processing chunk 452...
Processing chunk 453...
Processing chunk 454...
Processing chunk 455...
Processing chunk 456...
Processing chunk 457...
Processing chunk 458...
Processing chunk 459...
Processing chunk 460...
Processing chunk 461...
Processing chunk 462...
Processing chunk 463...
Processing chunk 464...
Processing chunk 465...
Processing chunk 466...
Processing chunk 467...
Processing chunk 468...
Processing chunk 469...
Processing chunk 470...
Processing chunk 471...
Processing chunk 472...
Processing chunk 473...
Processing chunk 474...
Processing chunk 475...
Processing chunk 476...
Processing chunk 477...
Processing chunk 478...
Processing chunk 479...
Processing chunk 480...
Processing chunk 481...
Processing chunk 482...
Processing chunk 483...
Processing chunk 484...
Processing chunk 485...
Processing chunk 486...
Processing chunk 487...
Processing chunk 488...
Processing chunk 489...
Processing chunk 490...
Processing chunk 491...
Processing chunk 492...
Processing chunk 493...
Processing chunk 494...
Processing chunk 495...
Processing chunk 496...
Processing chunk 497...
Processing chunk 498...
Processing chunk 499...
Processing chunk 500...
Processing chunk 501...
Processing chunk 502...
Processing chunk 503...
Processing chunk 504...
Processing chunk 505...
Processing chunk 506...
Processing chunk 507...
Processing chunk 508...
Processing chunk 509...
Processing chunk 510...
Processing chunk 511...
Processing chunk 512...
Processing chunk 513...
Processing chunk 514...
Processing chunk 515...
Processing chunk 516...
Processing chunk 517...
Processing chunk 518...
Processing chunk 519...
Processing chunk 520...
Processing chunk 521...
Processing chunk 522...
Processing chunk 523...
Processing chunk 524...
Processing chunk 525...
Processing chunk 526...
Processing chunk 527...
Processing chunk 528...
Processing chunk 529...
Processing chunk 530...
Processing chunk 531...
Processing chunk 532...
Processing chunk 533...
Processing chunk 534...
Processing chunk 535...
Processing chunk 536...
Processing chunk 537...
Processing chunk 538...
Processing chunk 539...
Processing chunk 540...
Processing chunk 541...
Processing chunk 542...
Processing chunk 543...
Processing chunk 544...
Processing chunk 545...
Processing chunk 546...
Processing chunk 547...
Processing chunk 548...
Processing chunk 549...
Processing chunk 550...
Processing chunk 551...
Processing chunk 552...
Processing chunk 553...
Processing chunk 554...
Processing chunk 555...
Processing chunk 556...
Processing chunk 557...
Processing chunk 558...
Processing chunk 559...
Processing chunk 560...
Processing chunk 561...
Processing chunk 562...
Processing chunk 563...
Processing chunk 564...
Processing chunk 565...
Processing chunk 566...
Processing chunk 567...
Processing chunk 568...
Processing chunk 569...
Processing chunk 570...
Processing chunk 571...
Processing chunk 572...
Processing chunk 573...
Processing chunk 574...
Processing chunk 575...
Processing chunk 576...
Processing chunk 577...
Processing chunk 578...
Processing chunk 579...
Processing chunk 580...
Processing chunk 581...
Processing chunk 582...
Processing chunk 583...
Processing chunk 584...
Processing chunk 585...
Processing chunk 586...
Processing chunk 587...
Processing chunk 588...
Processing chunk 589...
Processing chunk 590...
Processing chunk 591...
Processing chunk 592...
Processing chunk 593...
Processing chunk 594...
Processing chunk 595...
Processing chunk 596...
Processing chunk 597...
Processing chunk 598...
Processing chunk 599...
Processing chunk 600...
Processing chunk 601...
Processing chunk 602...
Processing chunk 603...
Processing chunk 604...
Processing chunk 605...
Processing chunk 606...
Processing chunk 607...
Processing chunk 608...
Processing chunk 609...
Processing chunk 610...
Processing chunk 611...
Processing chunk 612...
Processing chunk 613...
Processing chunk 614...
Processing chunk 615...
Processing chunk 616...
Processing chunk 617...
Processing chunk 618...
Processing chunk 619...
Processing chunk 620...
Processing chunk 621...
Processing chunk 622...
Processing chunk 623...
Processing chunk 624...
Processing chunk 625...
Processing chunk 626...
Processing chunk 627...
Processing chunk 628...
Processing chunk 629...
Processing chunk 630...
Processing chunk 631...
Processing chunk 632...
Processing chunk 633...
Processing chunk 634...
Processing chunk 635...
Processing chunk 636...
Processing chunk 637...
Processing chunk 638...
Processing chunk 639...
Processing chunk 640...
Processing chunk 641...
Processing chunk 642...
Processing chunk 643...
Processing chunk 644...
Processing chunk 645...
Processing chunk 646...
Processing chunk 647...
Processing chunk 648...
Processing chunk 649...
Processing chunk 650...
Processing chunk 651...
Processing chunk 652...
Processing chunk 653...
Processing chunk 654...
Processing chunk 655...
Processing chunk 656...
Processing chunk 657...
Processing chunk 658...
Processing chunk 659...
Processing chunk 660...
Processing chunk 661...
Processing chunk 662...
Processing chunk 663...
Processing chunk 664...
Processing chunk 665...
Processing chunk 666...
Processing chunk 667...
Processing chunk 668...
Processing chunk 669...
Processing chunk 670...
Processing chunk 671...
Processing chunk 672...
Processing chunk 673...
Processing chunk 674...
Processing chunk 675...
Processing chunk 676...
Processing chunk 677...
Processing chunk 678...
Processing chunk 679...
Processing chunk 680...
Processing chunk 681...
Processing chunk 682...
Processing chunk 683...
Processing chunk 684...
Processing chunk 685...
Processing chunk 686...
Processing chunk 687...
Processing chunk 688...
Processing chunk 689...
Processing chunk 690...
Processing chunk 691...
Processing chunk 692...
Processing chunk 693...
Processing chunk 694...
Processing chunk 695...
Processing chunk 696...
Processing chunk 697...
Processing chunk 698...
Processing chunk 699...
Processing chunk 700...
Processing chunk 701...
Processing chunk 702...
Processing chunk 703...
Processing chunk 704...
Processing chunk 705...
Processing chunk 706...
Processing chunk 707...
Processing chunk 708...
Processing chunk 709...
Processing chunk 710...
Processing chunk 711...
Processing chunk 712...
Processing chunk 713...
Processing chunk 714...
Processing chunk 715...
Processing chunk 716...
Processing chunk 717...
Processing chunk 718...
Processing chunk 719...
Processing chunk 720...
Processing chunk 721...
Processing chunk 722...
Processing chunk 723...
Processing chunk 724...
Processing chunk 725...
Processing chunk 726...
Processing chunk 727...
Processing chunk 728...
Processing chunk 729...
Processing chunk 730...
Processing chunk 731...
Processing chunk 732...
Processing chunk 733...
Processing chunk 734...
Processing chunk 735...
Processing chunk 736...
Processing chunk 737...
Processing chunk 738...
Processing chunk 739...
Processing chunk 740...
Processing chunk 741...
Processing chunk 742...
Processing chunk 743...
Processing chunk 744...
Processing chunk 745...
Processing chunk 746...
Processing chunk 747...
Processing chunk 748...
Processing chunk 749...
Processing chunk 750...
Processing chunk 751...
Processing chunk 752...
Processing chunk 753...
Processing chunk 754...
Processing chunk 755...
Processing chunk 756...
Processing chunk 757...
Processing chunk 758...
Processing chunk 759...
Processing chunk 760...
Processing chunk 761...
Processing chunk 762...
Processing chunk 763...
Processing chunk 764...
Processing chunk 765...
Processing chunk 766...
Processing chunk 767...
Processing chunk 768...
Processing chunk 769...
Processing chunk 770...
Processing chunk 771...
Processing chunk 772...
Processing chunk 773...
Processing chunk 774...
Processing chunk 775...
Processing chunk 776...
Processing chunk 777...
Processing chunk 778...
Processing chunk 779...
Processing chunk 780...
Processing chunk 781...
Processing chunk 782...
Processing chunk 783...
Processing chunk 784...
Processing chunk 785...
Processing chunk 786...
Processing chunk 787...
Processing chunk 788...
Processing chunk 789...
Processing chunk 790...
Processing chunk 791...
Processing chunk 792...
Processing chunk 793...
Processing chunk 794...
Processing chunk 795...
Processing chunk 796...
Processing chunk 797...
Processing chunk 798...
Processing chunk 799...
Processing chunk 800...
Processing chunk 801...
Processing chunk 802...
Processing chunk 803...
Processing chunk 804...
Processing chunk 805...
Processing chunk 806...
Processing chunk 807...
Processing chunk 808...
Processing chunk 809...
Processing chunk 810...
Processing chunk 811...
Processing chunk 812...
Processing chunk 813...
Processing chunk 814...
Processing chunk 815...
Processing chunk 816...
Processing chunk 817...
Processing chunk 818...
Processing chunk 819...
Processing chunk 820...
Processing chunk 821...
Processing chunk 822...
Processing chunk 823...
Processing chunk 824...
Processing chunk 825...
Processing chunk 826...
Processing chunk 827...
Processing chunk 828...
Processing chunk 829...
Processing chunk 830...
Processing chunk 831...
Processing chunk 832...
Processing chunk 833...
Processing chunk 834...
Processing chunk 835...
Processing chunk 836...
Processing chunk 837...

## reviews ENG

In [10]:
books_eng = pd.read_csv('ENG.csv')
book_ids = set(books_eng['book_id'])
# books_eng_mini = pd.read_csv('ENG.csv',nrows=10000)
# book_ids = set(books_eng_mini['book_id'])

json_file = "goodreads_reviews_dedup.json"
output_file = "reviews_ENG.csv"

chunksize = 10000
header_written = False
reviews_eng = 0

with open(output_file, "w", newline="", encoding="utf-8") as f:
    writer = None

    for i, chunk in enumerate(pd.read_json(json_file, lines=True, chunksize=chunksize)):
        print(f"Processing chunk {i+1}...")

        for _, row in chunk.iterrows():
            if row['book_id'] in book_ids:
                reviews_eng = reviews_eng + 1
                row_dict = row.to_dict()

                # Initialize writer once with headers
                if not header_written:
                    writer = csv.DictWriter(f, fieldnames=row_dict.keys())
                    writer.writeheader()
                    header_written = True

                # Write ONE row immediately
                writer.writerow(row_dict)

print("Done.")
print(f"ENG reviews count:{reviews_eng}")

# FRA reviews count:59.155
# ENG-mini reviews count:140.085 --> 110.000
# ENG reviews count: 11.409.758

Processing chunk 1...
Processing chunk 2...
Processing chunk 3...
Processing chunk 4...
Processing chunk 5...
Processing chunk 6...
Processing chunk 7...
Processing chunk 8...
Processing chunk 9...
Processing chunk 10...
Processing chunk 11...
Processing chunk 12...
Processing chunk 13...
Processing chunk 14...
Processing chunk 15...
Processing chunk 16...
Processing chunk 17...
Processing chunk 18...
Processing chunk 19...
Processing chunk 20...
Processing chunk 21...
Processing chunk 22...
Processing chunk 23...
Processing chunk 24...
Processing chunk 25...
Processing chunk 26...
Processing chunk 27...
Processing chunk 28...
Processing chunk 29...
Processing chunk 30...
Processing chunk 31...
Processing chunk 32...
Processing chunk 33...
Processing chunk 34...
Processing chunk 35...
Processing chunk 36...
Processing chunk 37...
Processing chunk 38...
Processing chunk 39...
Processing chunk 40...
Processing chunk 41...
Processing chunk 42...
Processing chunk 43...
Processing chunk 44...
Processing chunk 45...
Processing chunk 46...
Processing chunk 47...
Processing chunk 48...
Processing chunk 49...
Processing chunk 50...
Processing chunk 51...
Processing chunk 52...
Processing chunk 53...
Processing chunk 54...
Processing chunk 55...
Processing chunk 56...
Processing chunk 57...
Processing chunk 58...
Processing chunk 59...
Processing chunk 60...
Processing chunk 61...
Processing chunk 62...
Processing chunk 63...
Processing chunk 64...
Processing chunk 65...
Processing chunk 66...
Processing chunk 67...
Processing chunk 68...
Processing chunk 69...
Processing chunk 70...
Processing chunk 71...
Processing chunk 72...
Processing chunk 73...
Processing chunk 74...
Processing chunk 75...
Processing chunk 76...
Processing chunk 77...
Processing chunk 78...
Processing chunk 79...
Processing chunk 80...
Processing chunk 81...
Processing chunk 82...
Processing chunk 83...
Processing chunk 84...
Processing chunk 85...
Processing chunk 86...
Processing chunk 87...
Processing chunk 88...
Processing chunk 89...
Processing chunk 90...
Processing chunk 91...
Processing chunk 92...
Processing chunk 93...
Processing chunk 94...
Processing chunk 95...
Processing chunk 96...
Processing chunk 97...
Processing chunk 98...
Processing chunk 99...
Processing chunk 100...
Processing chunk 101...
Processing chunk 102...
Processing chunk 103...
Processing chunk 104...
Processing chunk 105...
Processing chunk 106...
Processing chunk 107...
Processing chunk 108...
Processing chunk 109...
Processing chunk 110...
Processing chunk 111...
Processing chunk 112...
Processing chunk 113...
Processing chunk 114...
Processing chunk 115...
Processing chunk 116...
Processing chunk 117...
Processing chunk 118...
Processing chunk 119...
Processing chunk 120...
Processing chunk 121...
Processing chunk 122...
Processing chunk 123...
Processing chunk 124...
Processing chunk 125...
Processing chunk 126...
Processing chunk 127...
Processing chunk 128...
Processing chunk 129...
Processing chunk 130...
Processing chunk 131...
Processing chunk 132...
Processing chunk 133...
Processing chunk 134...
Processing chunk 135...
Processing chunk 136...
Processing chunk 137...
Processing chunk 138...
Processing chunk 139...
Processing chunk 140...
Processing chunk 141...
Processing chunk 142...
Processing chunk 143...
Processing chunk 144...
Processing chunk 145...
Processing chunk 146...
Processing chunk 147...
Processing chunk 148...
Processing chunk 149...
Processing chunk 150...
Processing chunk 151...
Processing chunk 152...
Processing chunk 153...
Processing chunk 154...
Processing chunk 155...
Processing chunk 156...
Processing chunk 157...
Processing chunk 158...
Processing chunk 159...
Processing chunk 160...
Processing chunk 161...
Processing chunk 162...
Processing chunk 163...
Processing chunk 164...
Processing chunk 165...
Processing chunk 166...
Processing chunk 167...
Processing chunk 168...
Processing chunk 169...
Processing chunk 170...
Processing chunk 171...
Processing chunk 172...
Processing chunk 173...
Processing chunk 174...
Processing chunk 175...
Processing chunk 176...
Processing chunk 177...
Processing chunk 178...
Processing chunk 179...
Processing chunk 180...
Processing chunk 181...
Processing chunk 182...
Processing chunk 183...
Processing chunk 184...
Processing chunk 185...
Processing chunk 186...
Processing chunk 187...
Processing chunk 188...
Processing chunk 189...
Processing chunk 190...
Processing chunk 191...
Processing chunk 192...
Processing chunk 193...
Processing chunk 194...
Processing chunk 195...
Processing chunk 196...
Processing chunk 197...
Processing chunk 198...
Processing chunk 199...
Processing chunk 200...
Processing chunk 201...
Processing chunk 202...
Processing chunk 203...
Processing chunk 204...
Processing chunk 205...
Processing chunk 206...
Processing chunk 207...
Processing chunk 208...
Processing chunk 209...
Processing chunk 210...
Processing chunk 211...
Processing chunk 212...
Processing chunk 213...
Processing chunk 214...
Processing chunk 215...
Processing chunk 216...
Processing chunk 217...
Processing chunk 218...
Processing chunk 219...
Processing chunk 220...
Processing chunk 221...
Processing chunk 222...
Processing chunk 223...
Processing chunk 224...
Processing chunk 225...
Processing chunk 226...
Processing chunk 227...
Processing chunk 228...
Processing chunk 229...
Processing chunk 230...
Processing chunk 231...
Processing chunk 232...
Processing chunk 233...
Processing chunk 234...
Processing chunk 235...
Processing chunk 236...
Processing chunk 237...
Processing chunk 238...
Processing chunk 239...
Processing chunk 240...
Processing chunk 241...
Processing chunk 242...
Processing chunk 243...
Processing chunk 244...
Processing chunk 245...
Processing chunk 246...
Processing chunk 247...
Processing chunk 248...
Processing chunk 249...
Processing chunk 250...
Processing chunk 251...
Processing chunk 252...
Processing chunk 253...
Processing chunk 254...
Processing chunk 255...
Processing chunk 256...
Processing chunk 257...
Processing chunk 258...
Processing chunk 259...
Processing chunk 260...
Processing chunk 261...
Processing chunk 262...
Processing chunk 263...
Processing chunk 264...
Processing chunk 265...
Processing chunk 266...
Processing chunk 267...
Processing chunk 268...
Processing chunk 269...
Processing chunk 270...
Processing chunk 271...
Processing chunk 272...
Processing chunk 273...
Processing chunk 274...
Processing chunk 275...
Processing chunk 276...
Processing chunk 277...
Processing chunk 278...
Processing chunk 279...
Processing chunk 280...
Processing chunk 281...
Processing chunk 282...
Processing chunk 283...
Processing chunk 284...
Processing chunk 285...
Processing chunk 286...
Processing chunk 287...
Processing chunk 288...
Processing chunk 289...
Processing chunk 290...
Processing chunk 291...
Processing chunk 292...
Processing chunk 293...
Processing chunk 294...
Processing chunk 295...
Processing chunk 296...
Processing chunk 297...
Processing chunk 298...
Processing chunk 299...
Processing chunk 300...
Processing chunk 301...
Processing chunk 302...
Processing chunk 303...
Processing chunk 304...
Processing chunk 305...
Processing chunk 306...
Processing chunk 307...
Processing chunk 308...
Processing chunk 309...
Processing chunk 310...
Processing chunk 311...
Processing chunk 312...
Processing chunk 313...
Processing chunk 314...
Processing chunk 315...
Processing chunk 316...
Processing chunk 317...
Processing chunk 318...
Processing chunk 319...
Processing chunk 320...
Processing chunk 321...
Processing chunk 322...
Processing chunk 323...
Processing chunk 324...
Processing chunk 325...
Processing chunk 326...
Processing chunk 327...
Processing chunk 328...
Processing chunk 329...
Processing chunk 330...
Processing chunk 331...
Processing chunk 332...
Processing chunk 333...
Processing chunk 334...
Processing chunk 335...
Processing chunk 336...
Processing chunk 337...
Processing chunk 338...
Processing chunk 339...
Processing chunk 340...
Processing chunk 341...
Processing chunk 342...
Processing chunk 343...
Processing chunk 344...
Processing chunk 345...
Processing chunk 346...
Processing chunk 347...
Processing chunk 348...
Processing chunk 349...
Processing chunk 350...
Processing chunk 351...
Processing chunk 352...
Processing chunk 353...
Processing chunk 354...
Processing chunk 355...
Processing chunk 356...
Processing chunk 357...
Processing chunk 358...
Processing chunk 359...
Processing chunk 360...
Processing chunk 361...
Processing chunk 362...
Processing chunk 363...
Processing chunk 364...
Processing chunk 365...
Processing chunk 366...
Processing chunk 367...
Processing chunk 368...
Processing chunk 369...
Processing chunk 370...
Processing chunk 371...
Processing chunk 372...
Processing chunk 373...
Processing chunk 374...
Processing chunk 375...
Processing chunk 376...
Processing chunk 377...
Processing chunk 378...
Processing chunk 379...
Processing chunk 380...
Processing chunk 381...
Processing chunk 382...
Processing chunk 383...
Processing chunk 384...
Processing chunk 385...
Processing chunk 386...
Processing chunk 387...
Processing chunk 388...
Processing chunk 389...
Processing chunk 390...
Processing chunk 391...
Processing chunk 392...
Processing chunk 393...
Processing chunk 394...
Processing chunk 395...
Processing chunk 396...
Processing chunk 397...
Processing chunk 398...
Processing chunk 399...
Processing chunk 400...
Processing chunk 401...
Processing chunk 402...
Processing chunk 403...
Processing chunk 404...
Processing chunk 405...
Processing chunk 406...
Processing chunk 407...
Processing chunk 408...
Processing chunk 409...
Processing chunk 410...
Processing chunk 411...
Processing chunk 412...
Processing chunk 413...
Processing chunk 414...
Processing chunk 415...
Processing chunk 416...
Processing chunk 417...
Processing chunk 418...
Processing chunk 419...
Processing chunk 420...
Processing chunk 421...
Processing chunk 422...
Processing chunk 423...
Processing chunk 424...
Processing chunk 425...
Processing chunk 426...
Processing chunk 427...
Processing chunk 428...
Processing chunk 429...
Processing chunk 430...
Processing chunk 431...
Processing chunk 432...
Processing chunk 433...
Processing chunk 434...
Processing chunk 435...
Processing chunk 436...
Processing chunk 437...
Processing chunk 438...
Processing chunk 439...
Processing chunk 440...
Processing chunk 441...
Processing chunk 442...
Processing chunk 443...
Processing chunk 444...
Processing chunk 445...
Processing chunk 446...
Processing chunk 447...
Processing chunk 448...
Processing chunk 449...
Processing chunk 450...
Processing chunk 451...
Processing chunk 452...
Processing chunk 453...
Processing chunk 454...
Processing chunk 455...
Processing chunk 456...
Processing chunk 457...
Processing chunk 458...
Processing chunk 459...
Processing chunk 460...
Processing chunk 461...
Processing chunk 462...
Processing chunk 463...
Processing chunk 464...
Processing chunk 465...
Processing chunk 466...
Processing chunk 467...
Processing chunk 468...
Processing chunk 469...
Processing chunk 470...
Processing chunk 507...
Processing chunk 508...
Processing chunk 509...
Processing chunk 510...
Processing chunk 511...
Processing chunk 512...
Processing chunk 513...
Processing chunk 514...
Processing chunk 515...
Processing chunk 516...
Processing chunk 517...
Processing chunk 518...
Processing chunk 519...
Processing chunk 520...
Processing chunk 521...
Processing chunk 522...
Processing chunk 523...
Processing chunk 524...
Processing chunk 525...
Processing chunk 526...
Processing chunk 527...
Processing chunk 528...
Processing chunk 529...
Processing chunk 530...
Processing chunk 531...
Processing chunk 532...
Processing chunk 533...
Processing chunk 534...
Processing chunk 535...
Processing chunk 536...
Processing chunk 537...
Processing chunk 538...
Processing chunk 539...
Processing chunk 540...
Processing chunk 541...
Processing chunk 542...
Processing chunk 543...
Processing chunk 544...
Processing chunk 545...
Processing chunk 546...
Processing chunk 547...
Processing chunk 548...
Processing chunk 549...
Processing chunk 550...
Processing chunk 551...
Processing chunk 552...
Processing chunk 553...
Processing chunk 554...
Processing chunk 555...
Processing chunk 556...
Processing chunk 557...
Processing chunk 558...
Processing chunk 559...
Processing chunk 560...
Processing chunk 561...
Processing chunk 562...
Processing chunk 563...
Processing chunk 564...
Processing chunk 565...
Processing chunk 566...
Processing chunk 567...
Processing chunk 568...
Processing chunk 569...
Processing chunk 570...
Processing chunk 571...
Processing chunk 572...
Processing chunk 573...
Processing chunk 574...
Processing chunk 575...
Processing chunk 576...
Processing chunk 577...
Processing chunk 578...
Processing chunk 579...
Processing chunk 580...
Processing chunk 581...
Processing chunk 582...
Processing chunk 583...
Processing chunk 584...
Processing chunk 585...
Processing chunk 586...
Processing chunk 587...
Processing chunk 588...
Processing chunk 589...
Processing chunk 590...
Processing chunk 591...
Processing chunk 592...
Processing chunk 593...
Processing chunk 594...
Processing chunk 595...
Processing chunk 596...
Processing chunk 597...
Processing chunk 598...
Processing chunk 599...
Processing chunk 600...
Processing chunk 601...
Processing chunk 602...
Processing chunk 603...
Processing chunk 604...
Processing chunk 605...
Processing chunk 606...
Processing chunk 607...
Processing chunk 608...
Processing chunk 609...
Processing chunk 610...
Processing chunk 611...
Processing chunk 612...
Processing chunk 613...
Processing chunk 614...
Processing chunk 615...
Processing chunk 616...
Processing chunk 617...
Processing chunk 618...
Processing chunk 619...
Processing chunk 620...
Processing chunk 621...
Processing chunk 622...
Processing chunk 623...
Processing chunk 624...
Processing chunk 625...
Processing chunk 626...
Processing chunk 627...
Processing chunk 628...
Processing chunk 629...
Processing chunk 630...
Processing chunk 631...
Processing chunk 632...
Processing chunk 633...
Processing chunk 634...
Processing chunk 635...
Processing chunk 636...
Processing chunk 637...
Processing chunk 638...
Processing chunk 639...
Processing chunk 640...
Processing chunk 641...
Processing chunk 642...
Processing chunk 643...
Processing chunk 644...
Processing chunk 645...
Processing chunk 646...
Processing chunk 647...
Processing chunk 648...
Processing chunk 649...
Processing chunk 650...
Processing chunk 651...
Processing chunk 652...
Processing chunk 653...
Processing chunk 654...
Processing chunk 655...
Processing chunk 656...
Processing chunk 657...
Processing chunk 658...
Processing chunk 659...
Processing chunk 660...
Processing chunk 661...
Processing chunk 662...
Processing chunk 663...
Processing chunk 664...
Processing chunk 665...
Processing chunk 666...
Processing chunk 667...
Processing chunk 668...
Processing chunk 669...
Processing chunk 670...
Processing chunk 671...
Processing chunk 672...
Processing chunk 673...
Processing chunk 674...
Processing chunk 675...
Processing chunk 676...
Processing chunk 677...
Processing chunk 678...
Processing chunk 679...
Processing chunk 680...
Processing chunk 681...
Processing chunk 682...
Processing chunk 683...
Processing chunk 684...
Processing chunk 685...
Processing chunk 686...
Processing chunk 687...
Processing chunk 688...
Processing chunk 689...
Processing chunk 690...
Processing chunk 691...
Processing chunk 692...
Processing chunk 693...
Processing chunk 694...
Processing chunk 695...
Processing chunk 696...
Processing chunk 697...
Processing chunk 698...
Processing chunk 699...
Processing chunk 700...
Processing chunk 701...
Processing chunk 702...
Processing chunk 703...
Processing chunk 704...
Processing chunk 705...
Processing chunk 706...
Processing chunk 707...
Processing chunk 708...
Processing chunk 709...
Processing chunk 710...
Processing chunk 711...
Processing chunk 712...
Processing chunk 713...
Processing chunk 714...
Processing chunk 715...
Processing chunk 716...
Processing chunk 717...
Processing chunk 718...
Processing chunk 719...
Processing chunk 720...
Processing chunk 721...
Processing chunk 722...
Processing chunk 723...
Processing chunk 724...
Processing chunk 725...
Processing chunk 726...
Processing chunk 727...
Processing chunk 728...
Processing chunk 729...
Processing chunk 730...
Processing chunk 731...
Processing chunk 732...
Processing chunk 733...
Processing chunk 734...
Processing chunk 735...
Processing chunk 736...
Processing chunk 737...
Processing chunk 738...
Processing chunk 739...
Processing chunk 740...
Processing chunk 741...
Processing chunk 742...
Processing chunk 743...
Processing chunk 744...
Processing chunk 745...
Processing chunk 746...
Processing chunk 747...
Processing chunk 748...
Processing chunk 749...
Processing chunk 750...
Processing chunk 751...
Processing chunk 752...
Processing chunk 753...
Processing chunk 754...
Processing chunk 755...
Processing chunk 756...
Processing chunk 757...
Processing chunk 758...
Processing chunk 759...
Processing chunk 760...
Processing chunk 761...
Processing chunk 762...
Processing chunk 763...
Processing chunk 764...
Processing chunk 765...
Processing chunk 766...
Processing chunk 767...
Processing chunk 768...
Processing chunk 769...
Processing chunk 770...
Processing chunk 771...
Processing chunk 772...
Processing chunk 773...
Processing chunk 774...
Processing chunk 775...
Processing chunk 776...
Processing chunk 777...
Processing chunk 778...
Processing chunk 779...
Processing chunk 780...
Processing chunk 781...
Processing chunk 782...
Processing chunk 783...
Processing chunk 784...
Processing chunk 785...
Processing chunk 786...
Processing chunk 787...
Processing chunk 788...
Processing chunk 789...
Processing chunk 790...
Processing chunk 791...
Processing chunk 792...
Processing chunk 793...
Processing chunk 794...
Processing chunk 795...
Processing chunk 796...
Processing chunk 797...
Processing chunk 798...
Processing chunk 799...
Processing chunk 800...
Processing chunk 801...
Processing chunk 802...
Processing chunk 803...
Processing chunk 804...
Processing chunk 805...
Processing chunk 806...
Processing chunk 807...
Processing chunk 808...
Processing chunk 809...
Processing chunk 810...
Processing chunk 811...
Processing chunk 812...
Processing chunk 813...
Processing chunk 814...
Processing chunk 815...
Processing chunk 816...
Processing chunk 817...
Processing chunk 818...
Processing chunk 819...
Processing chunk 820...
Processing chunk 821...
Processing chunk 822...
Processing chunk 823...
Processing chunk 824...
Processing chunk 825...
Processing chunk 826...
Processing chunk 827...
Processing chunk 828...
Processing chunk 829...
Processing chunk 830...
Processing chunk 831...
Processing chunk 832...
Processing chunk 833...
Processing chunk 834...
Processing chunk 835...
Processing chunk 836...
Processing chunk 837...
Processing chunk 838...
Processing chunk 839...
Processing chunk 840...
Processing chunk 841...
Processing chunk 842...
Processing chunk 843...
Processing chunk 844...
Processing chunk 845...
Processing chunk 846...
Processing chunk 847...
Processing chunk 848...
Processing chunk 849...
Processing chunk 850...
Processing chunk 851...
Processing chunk 852...
Processing chunk 853...
Processing chunk 854...
Processing chunk 855...
Processing chunk 856...
Processing chunk 857...
Processing chunk 858...
Processing chunk 859...
Processing chunk 860...
Processing chunk 861...
Processing chunk 862...
Processing chunk 863...
Processing chunk 864...
Processing chunk 865...
Processing chunk 866...
Processing chunk 867...
Processing chunk 868...
Processing chunk 869...
Processing chunk 870...
Processing chunk 871...
Processing chunk 872...
Processing chunk 873...

In [5]:
books_mini = pd.read_csv('reviews_ENG_mini.csv')

In [9]:
books_eng_mini.to_csv("books_ENG_mini.csv", index=False)

# 📝 Review investigation

In [113]:
reviews_small.sample(3)

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
508,01ec1a320ffded6b2dd47833f2c8e4fb,28331788,e1879094f83a75b4b243a1da92f79ad5,4,OMG Chandler is SCRUMMY!! An unexpectedly funn...,Thu Sep 15 16:53:15 -0700 2016,Sun Sep 25 22:12:15 -0700 2016,Tue Sep 20 00:00:00 -0700 2016,,12,0
7572,a61ed781e6722c23306fb73d45eb8ecc,20420321,68155e7132f63a8ac05cd64ff3bdc85d,5,I should preface this that I have always been ...,Thu Mar 31 12:30:42 -0700 2016,Sat May 07 17:27:07 -0700 2016,Fri Apr 01 00:00:00 -0700 2016,Thu Mar 31 00:00:00 -0700 2016,0,0
638,01ec1a320ffded6b2dd47833f2c8e4fb,28230547,047b24de0e2fed0161b43eb7ffafd8bf,5,Slip of the Tongue is absolutely enthralling. ...,Thu Dec 17 05:54:14 -0800 2015,Thu Mar 03 00:12:07 -0800 2016,Sat Feb 27 00:00:00 -0800 2016,Wed Feb 24 00:00:00 -0800 2016,154,13

In [124]:
def preprocessing(sentence):

    lemmatizer = WordNetLemmatizer()

    # Basic cleaning
    sentence = sentence.strip()
    sentence = sentence.lower()

    # Remove accents 
    sentence = ''.join(
        c for c in unicodedata.normalize('NFD', sentence)
        if unicodedata.category(c) != 'Mn'
    )

    # Remove numbers
    sentence = ''.join(char for char in sentence if not char.isdigit())

    # Remove punctuation
    sentence = sentence.translate(str.maketrans('', '', string.punctuation))

    # Tokenize
    tokenized_sentence = word_tokenize(sentence)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokenized_sentence_cleaned = [
        w for w in tokenized_sentence if w not in stop_words
    ]

    # Lemmatize verbs
    verb_lemmatized = [
        lemmatizer.lemmatize(word, pos="v")
        for word in tokenized_sentence_cleaned
    ]

    # Lemmatize nouns
    noun_lemmatized = [
        lemmatizer.lemmatize(word, pos="n")
        for word in verb_lemmatized
    ]

    # Join back
    cleaned_sentence = ' '.join(noun_lemmatized)

    return cleaned_sentence

In [146]:
# data = reviews_small[['rating','n_votes','n_comments','riview_text']].copy()
data = reviews_small[['rating','review_text']].copy()
data.columns = ['score','message']
# data['score'].value_counts()
data = data[data.score<3]
data['clean_text'] = data["message"].apply(preprocessing)
data.sample(5)

,score,message,clean_text
4153,2,"Paljon hypetetty, mutta kovin ohueksi jaava ro...",paljon hypetetty mutta kovin ohueksi jaava rom...
3493,1,WEIRD BOOK!!!!,weird book
8171,0,It took a little while for this book to hit it...,take little book hit stride really take pro al...
7374,0,not now,
3695,2,Very different from the movie - here Forrest w...,different movie forrest wind go space crash la...

In [154]:
# Instantiating the TfidfVectorizer
tf_idf_vectorizer = TfidfVectorizer(
    ngram_range=(3,3),
    min_df=5,          # très important pour réduire la taille
    max_features=10000 # optionnel mais recommandé
)

# Training it on the texts
X = tf_idf_vectorizer.fit_transform(data['clean_text'])

# Créer un DataFrame SPARSE (pas dense !)
weighted_words = pd.DataFrame.sparse.from_spmatrix(
    X,
    columns=tf_idf_vectorizer.get_feature_names_out()
)
weighted_words

,book ive read,didnt like book,didnt really care,dont want read,earc book courtesy,ei mikaan erikoinen,exchange honest review,finish read book,full review httpchickloveslitcomrevi,give book star,...,mikaan erikoinen kirja,note receive free,oli ihan ok,read book dont,really want like,receive free copy,see full review,time read book,want like book,want read book
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1308,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1309,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1310,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1311,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [159]:
# Instantiate the LDA
n_components = 3
lda_model = LatentDirichletAllocation(
    n_components=n_components, 
    max_iter = 100)

# Fit the LDA on the vectorized documents
lda_model.fit(weighted_words)

LatentDirichletAllocation(max_iter=100, n_components=3)

In [160]:
document_topic_mixture = lda_model.transform(weighted_words)
document_topic_mixture
topic_word_mixture = pd.DataFrame(
    lda_model.components_,
    columns = tf_idf_vectorizer.get_feature_names_out()
)
topic_word_mixture

,book ive read,didnt like book,didnt really care,dont want read,earc book courtesy,ei mikaan erikoinen,exchange honest review,finish read book,full review httpchickloveslitcomrevi,give book star,...,mikaan erikoinen kirja,note receive free,oli ihan ok,read book dont,really want like,receive free copy,see full review,time read book,want like book,want read book
0,0.335680,0.342996,0.336030,0.335784,0.336233,6.231566,0.335232,0.335668,0.337107,0.335769,...,5.328265,0.334687,0.336030,4.743803,0.337156,0.334687,24.329303,4.743803,0.351684,6.854149
1,0.335344,6.019406,5.328097,0.335433,5.026997,0.334779,0.334962,0.335334,36.924294,0.335420,...,0.334680,0.334495,5.328097,0.335117,0.335131,0.334495,0.335254,0.335117,0.335440,0.338839
2,7.019611,0.336017,0.335873,5.328783,0.343877,0.334922,8.250900,5.052201,0.335819,6.328811,...,0.334813,3.894580,0.335873,0.335294,7.766456,3.894580,0.335444,0.335294,8.658247,0.340070

In [161]:
def print_topics(lda_model, vectorizer, top_words):
    # 1. TOPIC MIXTURE OF WORDS FOR EACH TOPIC
    topic_mixture = pd.DataFrame(
        lda_model.components_,
        columns = vectorizer.get_feature_names_out()
    )

    # 2. FINDING THE TOP WORDS FOR EACH TOPIC
    ## Number of topics
    n_components = topic_mixture.shape[0]

    ## Top words for each topic
    for topic in range(n_components):
        print("-"*10)
        print(f"For topic {topic}, here are the the top {top_words} words with weights:")

        topic_df = topic_mixture.iloc[topic]\
            .sort_values(ascending = False).head(top_words)

        print(round(topic_df,3))

print_topics(lda_model, tf_idf_vectorizer, 10)

----------
For topic 0, here are the the top 10 words with weights:
see full review           24.329
want read book             6.854
ei mikaan erikoinen        6.232
mikaan erikoinen kirja     5.328
time read book             4.744
read book dont             4.744
like book didnt            4.102
want like book             0.352
didnt like book            0.343
really want like           0.337
Name: 0, dtype: float64
----------
For topic 1, here are the the top 10 words with weights:
full review httpchickloveslitcomrevi    36.924
look forward read                        7.328
didnt like book                          6.019
didnt really care                        5.328
oli ihan ok                              5.328
earc book courtesy                       5.027
like book didnt                          0.344
like main character                      0.342
want read book                           0.339
want like book                           0.335
Name: 1, dtype: float64
----------
For topic 2, here are the the top 10 words with weights:
want like book            8.658
exchange honest review    8.251
really want like          7.766
book ive read             7.020
give book star            6.329
dont want read            5.329
finish read book          5.052
like main character       4.776
receive free copy         3.895
note receive free         3.895
Name: 2, dtype: float64

# 📕my books

In [58]:
book_ids = [
100975480, 244298525, 240387017, 148026577, 229020641, 114878170,
227825134, 42816183, 59511686, 18593476, 48852556, 220463842,
13582068, 24242361, 46147115, 60829192, 8153621, 223056077,
57847020, 58051481, 222282333, 36388099, 18193649, 28445788,
222428605, 61327464, 62362630, 199551453, 2688375, 9479886,
228998792, 228712145, 60556912, 63886589, 43696271, 43925876,
23448409, 40665488, 18619684, 35691924, 9969571, 16132940,
12530077, 44662799, 60706125, 228715902, 57106839, 58048243,
57515678, 27774596, 3026117, 59787389, 217431603, 35598549,
229056249, 216905177, 210548133, 13490260, 10084651, 3141974,
218395095, 234735622, 3947021, 32499981, 127305853, 5974221,
28104958, 11038479, 235627708, 8471831, 123068620, 61334309,
209062073, 126763858, 230417959, 30063601, 8663639, 204276986,
60018212, 175194515, 206000594, 205456651, 23456312, 23716877,
211427271, 6749970, 37640479, 40511037, 18131826, 34862618,
180337481, 12986195, 156763685, 18745785, 39292158, 18632412,
210402635, 12985084, 40720369, 123098283, 42014665, 221078632,
63275603, 222195622, 50849436, 8663314, 1075704, 12395413,
63259184, 205625418, 220869574, 214211465, 57280590, 42192403,
55823541, 209603176, 20442293, 58608114, 66095958, 122765395,
198902277, 4865, 194802722, 164444179, 35323041, 17984552,
160267078, 11468377, 40121378, 24770, 61376452, 16026429,
30848103, 58156671, 23267014, 36582882, 51889777, 55512357,
50625669, 24894451, 161666240, 12403881, 63856651, 56127955,
41135036, 51277261, 62610190, 26308335, 49004313, 18395113,
11122772, 6298297, 56028895, 53877746, 43563201, 39918821,
38743083, 36157052, 8122667, 11607, 807211, 1912426,
28787462, 9736930, 39146386, 18111060, 3042181, 2429135,
2767052, 968, 10139022, 36191087, 32597558, 6186357,
1422371, 466405, 10392065, 7789885
]
# books_dut = pd.read_csv('DUT.csv')
# books_dut[books_dut['book_id'].isin(book_ids)]
books_fra = pd.read_csv('FRA.csv')
books_fra[books_fra['book_id'].isin(book_ids)]

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,similar_books,description,format,link,authors,publisher,num_pages,publication_day,isbn13,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
5225,2845635230,117.0,[],US,fre,"[{'count': '63', 'name': 'to-read'}, {'count':...",NaN,False,3.58,NaN,"['18693967', '17856011', '20412983', '6085158'...",Un divorce les avait separes...\n... le danger...,broche,https://www.goodreads.com/book/show/13582068-7...,"[{'author_id': '282080', 'role': ''}]",XO Editions,400.0,5.0,9782845635234,4.0,NaN,2012.0,https://www.goodreads.com/book/show/13582068-7...,https://images.gr-assets.com/books/1333787736m...,13582068,2274.0,19167798.0,7 ans après...,7 ans après...
5506,2845635176,272.0,['1043594'],US,fre,"[{'count': '243', 'name': 'currently-reading'}...",NaN,False,4.02,NaN,"['18693967', '15705598', '17856011', '2907967'...","Dans leur telephone, il y avait toute leur vie...",Paperback,https://www.goodreads.com/book/show/10392065-l...,"[{'author_id': '282080', 'role': ''}]",XO,391.0,31.0,9782845635173,3.0,NaN,2011.0,https://www.goodreads.com/book/show/10392065-l...,https://images.gr-assets.com/books/1327457788m...,10392065,4632.0,15295848.0,L'appel de l'ange,L'appel de l'ange
5697,2845634579,367.0,[],US,fre,"[{'count': '7078', 'name': 'to-read'}, {'count...",NaN,False,4.03,NaN,"['182671', '20412983', '6085158', '7375409', '...","Tom Boyd, un ecrivain celebre en panne d'inspi...",Paperback,https://www.goodreads.com/book/show/7789885-la...,"[{'author_id': '282080', 'role': ''}, {'author...",XO Editions,376.0,31.0,9782845634572,3.0,NaN,2010.0,https://www.goodreads.com/book/show/7789885-la...,https://images.gr-assets.com/books/1327425654m...,7789885,5272.0,10740837.0,La fille de papier,La fille de papier
10626,2845638086,157.0,[],US,fre,"[{'count': '1439', 'name': 'to-read'}, {'count...",NaN,False,4.03,NaN,"['26790313', '1992867', '7949687', '26242071',...",Je me souviens tres bien de cet instant. Nous ...,Paperback,https://www.goodreads.com/book/show/28787462-l...,"[{'author_id': '282080', 'role': ''}]",XO Editions,473.0,24.0,9782845638082,3.0,NaN,2016.0,https://www.goodreads.com/book/show/28787462-l...,https://images.gr-assets.com/books/1457180268m...,28787462,1513.0,48996117.0,La fille de Brooklyn,La fille de Brooklyn
17201,2266023039,137.0,[],US,fre,"[{'count': '941', 'name': 'to-read'}, {'count'...",NaN,False,4.12,B00PCYXS08,"['122372', '1393631', '1397743', '1485778', '1...","Dans l'immense paysage gele, les membres des E...",Mass Market Paperback,https://www.goodreads.com/book/show/466405.La_...,"[{'author_id': '61797', 'role': ''}]",Pocket,394.0,NaN,9782266023030,NaN,NaN,NaN,https://www.goodreads.com/book/show/466405.La_...,https://s.gr-assets.com/assets/nophoto/book/11...,466405,4348.0,102892.0,La Nuit des temps,La Nuit des temps
30358,2253151394,28.0,[],US,fre,"[{'count': '6676', 'name': 'to-read'}, {'count...",NaN,False,4.11,NaN,"['66370', '11532', '179735', '25436970', '6980...",Mieux que le marathon... la Longue Marche. Cen...,Mass Market Paperback,https://www.goodreads.com/book/show/1422371.Ma...,"[{'author_id': '5858', 'role': 'Pseudonym'}, {...",Livre de Poche,378.0,12.0,9782253151395,1.0,NaN,2004.0,https://www.goodreads.com/book/show/1422371.Ma...,https://s.gr-assets.com/assets/nophoto/book/11...,1422371,349.0,522169.0,Marche ou crève,Marche ou crève