In [8]:
%load_ext autoreload
%autoreload 2

import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

file_name = '/home/christel/code/bigjo6/my_shelves/data/books_ENG_mini.csv'
data = pd.read_csv(file_name)
data.head()

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,similar_books,description,format,link,authors,publisher,num_pages,publication_day,isbn13,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
0,NaN,7,['189911'],US,eng,"[{'count': '58', 'name': 'to-read'}, {'count':...",B00071IKUY,False,4.03,NaN,"['19997', '828466', '1569323', '425389', '1176...",Omnibus book club edition containing the Ladie...,Hardcover,https://www.goodreads.com/book/show/7327624-th...,"[{'author_id': '10333', 'role': ''}]","Nelson Doubleday, Inc.",600.0,NaN,NaN,NaN,Book Club Edition,1987.0,https://www.goodreads.com/book/show/7327624-th...,https://images.gr-assets.com/books/1304100136m...,7327624,140,8948723,"The Unschooled Wizard (Sun Wolf and Starhawk, ...","The Unschooled Wizard (Sun Wolf and Starhawk, ..."
1,0743294297,3282,[],US,eng,"[{'count': '7615', 'name': 'to-read'}, {'count...",NaN,False,3.49,B002ENBLOK,"['6604176', '6054190', '2285777', '82641', '75...",Addie Downs and Valerie Adler were eight when ...,Hardcover,https://www.goodreads.com/book/show/6066819-be...,"[{'author_id': '9212', 'role': ''}]",Atria Books,368.0,14.0,9780743294294,7.0,NaN,2009.0,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,6066819,51184,6243154,Best Friends Forever,Best Friends Forever
2,NaN,60,['1052227'],US,eng,"[{'count': '54', 'name': 'currently-reading'},...",B01NCIKAQX,True,4.33,B01NCIKAQX,[],NaN,NaN,https://www.goodreads.com/book/show/33394837-t...,"[{'author_id': '242185', 'role': ''}]",NaN,318.0,NaN,NaN,NaN,NaN,NaN,https://www.goodreads.com/book/show/33394837-t...,https://images.gr-assets.com/books/1493114742m...,33394837,269,54143148,The House of Memory (Pluto's Snitch #2),The House of Memory (Pluto's Snitch #2)
3,555118000X,19,[],US,eng,"[{'count': '3488', 'name': 'to-read'}, {'count...",NaN,False,3.82,NaN,"['415854', '45794', '871284', '12881', '11662'...",NaN,NaN,https://www.goodreads.com/book/show/89373.The_...,"[{'author_id': '3083854', 'role': ''}]",NaN,NaN,NaN,9785551180005,NaN,NaN,NaN,https://www.goodreads.com/book/show/89373.The_...,https://s.gr-assets.com/assets/nophoto/book/11...,89373,77,1080201,The Bonfire of the Vanities,The Bonfire of the Vanities
4,0842379428,566,[],US,eng,"[{'count': '6393', 'name': 'to-read'}, {'count...",NaN,False,4.26,B000FCKCJC,"['45366', '246849', '11096385', '19102466', '7...",What is Heaven really going to be like? What w...,NaN,https://www.goodreads.com/book/show/89376.Heaven,"[{'author_id': '4862', 'role': ''}]",NaN,533.0,NaN,9780842379427,NaN,NaN,NaN,https://www.goodreads.com/book/show/89376.Heaven,https://images.gr-assets.com/books/1406508230m...,89376,7345,86257,Heaven,Heaven

In [4]:
data.columns.to_list()

['isbn',
 'text_reviews_count',
 'series',
 'country_code',
 'language_code',
 'popular_shelves',
 'asin',
 'is_ebook',
 'average_rating',
 'kindle_asin',
 'similar_books',
 'description',
 'format',
 'link',
 'authors',
 'publisher',
 'num_pages',
 'publication_day',
 'isbn13',
 'publication_month',
 'edition_information',
 'publication_year',
 'url',
 'image_url',
 'book_id',
 'ratings_count',
 'work_id',
 'title',
 'title_without_series']

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   isbn                  5058 non-null   str
 1   text_reviews_count    10000 non-null  int64
 2   series                10000 non-null  str
 3   country_code          10000 non-null  str
 4   language_code         10000 non-null  str
 5   popular_shelves       10000 non-null  str
 6   asin                  2725 non-null   str
 7   is_ebook              10000 non-null  bool
 8   average_rating        10000 non-null  float64
 9   kindle_asin           5197 non-null   str
 10  similar_books         10000 non-null  str
 11  description           9090 non-null   str
 12  format                7555 non-null   str
 13  link                  10000 non-null  str
 14  authors               10000 non-null  str
 15  publisher             7275 non-null   str
 16  num_pages             6960 non-null   float64
 17  publication_day       6355 non-null   float64
 18  isbn13                5789 non-null   str
 19  publication_month     6824 non-null   float64
 20  edition_information   1259 non-null   str
 21  publication_year      7791 non-null   float64
 22  url                   10000 non-null  str
 23  image_url             10000 non-null  str
 24  book_id               10000 non-null  int64
 25  ratings_count         10000 non-null  int64
 26  work_id               10000 non-null  int64
 27  title                 10000 non-null  str
 28  title_without_series  10000 non-null  str
dtypes: bool(1), float64(5), int64(4), str(19)
memory usage: 2.1 MB

In [ ]:
col_to_drop = ['publication_day', 'publication_month', 'isbn', 'asin', 'kindle_asin', 'format', 'isbn13', 'edition_information', 'work_id', 'link']

In [ ]:
col_to_add = ['sentiment', 'rythme', 'genre', 'author', 'location', 'period', 'content_intensity', 'romance_heat_level', 'is_serie', 'popular_shelves_read' , 'popular_shelves_to_read']

In [16]:
data_light = data.copy().drop(columns=col_to_drop)
data_light.head()

,text_reviews_count,series,country_code,language_code,popular_shelves,is_ebook,average_rating,similar_books,description,link,authors,publisher,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
0,7,['189911'],US,eng,"[{'count': '58', 'name': 'to-read'}, {'count':...",False,4.03,"['19997', '828466', '1569323', '425389', '1176...",Omnibus book club edition containing the Ladie...,https://www.goodreads.com/book/show/7327624-th...,"[{'author_id': '10333', 'role': ''}]","Nelson Doubleday, Inc.",1987.0,https://www.goodreads.com/book/show/7327624-th...,https://images.gr-assets.com/books/1304100136m...,7327624,140,8948723,"The Unschooled Wizard (Sun Wolf and Starhawk, ...","The Unschooled Wizard (Sun Wolf and Starhawk, ..."
1,3282,[],US,eng,"[{'count': '7615', 'name': 'to-read'}, {'count...",False,3.49,"['6604176', '6054190', '2285777', '82641', '75...",Addie Downs and Valerie Adler were eight when ...,https://www.goodreads.com/book/show/6066819-be...,"[{'author_id': '9212', 'role': ''}]",Atria Books,2009.0,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,6066819,51184,6243154,Best Friends Forever,Best Friends Forever
2,60,['1052227'],US,eng,"[{'count': '54', 'name': 'currently-reading'},...",True,4.33,[],NaN,https://www.goodreads.com/book/show/33394837-t...,"[{'author_id': '242185', 'role': ''}]",NaN,NaN,https://www.goodreads.com/book/show/33394837-t...,https://images.gr-assets.com/books/1493114742m...,33394837,269,54143148,The House of Memory (Pluto's Snitch #2),The House of Memory (Pluto's Snitch #2)
3,19,[],US,eng,"[{'count': '3488', 'name': 'to-read'}, {'count...",False,3.82,"['415854', '45794', '871284', '12881', '11662'...",NaN,https://www.goodreads.com/book/show/89373.The_...,"[{'author_id': '3083854', 'role': ''}]",NaN,NaN,https://www.goodreads.com/book/show/89373.The_...,https://s.gr-assets.com/assets/nophoto/book/11...,89373,77,1080201,The Bonfire of the Vanities,The Bonfire of the Vanities
4,566,[],US,eng,"[{'count': '6393', 'name': 'to-read'}, {'count...",False,4.26,"['45366', '246849', '11096385', '19102466', '7...",What is Heaven really going to be like? What w...,https://www.goodreads.com/book/show/89376.Heaven,"[{'author_id': '4862', 'role': ''}]",NaN,NaN,https://www.goodreads.com/book/show/89376.Heaven,https://images.gr-assets.com/books/1406508230m...,89376,7345,86257,Heaven,Heaven

In [9]:
file_name = '/home/christel/code/bigjo6/my_shelves/data/reviews_ENG_mini.csv'
reviews = pd.read_csv(file_name)
reviews.head()

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,19398490,ea4a220b10e6b5c796dae0e3b970aff1,4,A beautiful story. It is rare to encounter a b...,Sun Jan 03 21:20:46 -0800 2016,Tue Sep 20 23:30:15 -0700 2016,Tue Sep 13 11:51:51 -0700 2016,Sat Aug 20 07:03:03 -0700 2016,35,5
1,8842281e1d1347389f2ab93d60773d4d,8664353,da2d4cfce836a2c57ad55c38437aa692,5,"Wow. Amazing story, and well told - kept me up...",Sun Nov 20 09:10:15 -0800 2011,Wed Mar 22 11:47:04 -0700 2017,Wed May 16 00:00:00 -0700 2012,Sun May 06 00:00:00 -0700 2012,50,4
2,01ec1a320ffded6b2dd47833f2c8e4fb,27878417,b22dd337ee1938dd7cac80261aed6d2f,5,Contains major spoilers so only read this afte...,Mon Nov 16 21:35:17 -0800 2015,Sun Dec 06 22:45:19 -0800 2015,Wed Nov 18 11:06:15 -0800 2015,Mon Nov 16 00:00:00 -0800 2015,16,0
3,01ec1a320ffded6b2dd47833f2c8e4fb,23518092,39afe8c459a61c9d66fe212217608d72,4,"This is a juicy, fast-paced and totally enjoya...",Sun Jan 18 22:08:52 -0800 2015,Sun Jan 18 22:09:49 -0800 2015,Sun Jan 18 00:00:00 -0800 2015,NaN,6,2
4,01ec1a320ffded6b2dd47833f2c8e4fb,23350137,544dca1efd8819f93996a20fec44f199,4,"This is a fun, loving, sexy and very satisfyin...",Sun Nov 30 23:05:08 -0800 2014,Tue Dec 02 08:25:58 -0800 2014,Mon Dec 01 00:00:00 -0800 2014,Sun Nov 30 00:00:00 -0800 2014,6,0

In [17]:
reviews.columns.to_list()

['user_id',
 'book_id',
 'review_id',
 'rating',
 'review_text',
 'date_added',
 'date_updated',
 'read_at',
 'started_at',
 'n_votes',
 'n_comments']

In [ ]:
reviews.groupby('review_id')['n_votes'].sum().sort_values(ascending=False)

review_id
be50b7406fcff1770b983f53ce55aa37    1366
16d702f692ad6af2cb4fda4bfd30f9b6     691
5e699bf0b6f3584651c48a0427b3bb38     505
14ab5da72fae07b10efa2db30aa99bcd     486
9d4dc4928cda567b778347e05d7af580     349
                                    ...
a0037457c356160faafc815c6dc90252      -1
f1b57ce3fb04c63d22d17f8d00381c86      -2
4df5341e1c75fd163021a9fa0e749f97      -2
4588b28a75ce0e7dc2ad88481303fc8b      -2
2189d7d62b61deb7ce310151a7b32e6a      -2
Name: n_votes, Length: 110000, dtype: int64

In [20]:
reviews.loc[reviews['n_votes']<0]

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
25564,f2715e6c557354ea3beb7639efec8124,10356101,a0037457c356160faafc815c6dc90252,3,I decided to sneak in another Sherlock Holmes ...,Sat Mar 30 11:34:33 -0700 2013,Thu Oct 27 13:29:15 -0700 2016,Sun Mar 31 00:00:00 -0700 2013,Sat Mar 30 00:00:00 -0700 2013,-1,0
37482,59754892ed4fcec0fb6776b2d819b6df,13449673,de7bba8b656d17aa5c55ea0852b859d0,5,The author creates a puzzle that the reader mu...,Wed Apr 18 11:41:43 -0700 2012,Mon Nov 03 14:33:29 -0800 2014,Fri Apr 20 00:00:00 -0700 2012,Wed Apr 18 00:00:00 -0700 2012,-1,0
37486,59754892ed4fcec0fb6776b2d819b6df,175242,2189d7d62b61deb7ce310151a7b32e6a,4,NYPD detective Charlie Parker's wife and daugh...,Fri May 01 19:07:52 -0700 2009,Mon Nov 03 14:01:44 -0800 2014,Fri May 18 00:00:00 -0700 2012,NaN,-2,0
40597,fc16782b4417ed9c7c0af55c8a503274,6320534,c05dae62ee65b763a69a0231a5ca59d7,3,I don't really know what to say about this boo...,Sat Aug 03 06:09:09 -0700 2013,Mon Nov 03 14:51:48 -0800 2014,Sun Nov 03 00:00:00 -0700 2013,Sat Aug 03 00:00:00 -0700 2013,-1,1
44887,e611df70e380135b0e38d958bbe31a12,8044557,d886c033980879d89292a4edf47cdaf5,3,A picture book for adults who need a little ch...,Mon Jan 14 06:05:19 -0800 2013,Mon Jan 14 09:16:24 -0800 2013,Mon Jan 14 09:16:24 -0800 2013,Mon Jan 14 00:00:00 -0800 2013,-1,1
67776,6ad34915d4981873b6544a5d1d3451a1,2379178,4df5341e1c75fd163021a9fa0e749f97,4,Cockatiels at Seven by Donna Andrews was a goo...,Wed Mar 05 05:24:29 -0800 2014,Mon Nov 03 15:00:19 -0800 2014,Sat Mar 08 00:00:00 -0800 2014,Wed Mar 05 00:00:00 -0800 2014,-2,0
67778,6ad34915d4981873b6544a5d1d3451a1,5181966,f1b57ce3fb04c63d22d17f8d00381c86,4,There is an important question that you must a...,Sun Sep 15 08:30:11 -0700 2013,Mon Nov 03 14:53:46 -0800 2014,Sat Sep 21 11:13:10 -0700 2013,Sun Sep 15 00:00:00 -0700 2013,-2,0
67779,6ad34915d4981873b6544a5d1d3451a1,12987151,b848c7546d73ce1ea908ce2761c54b00,5,Madhatten Mystery by John J. Bonk is the perfe...,Fri Jun 29 06:30:12 -0700 2012,Mon Nov 03 14:36:08 -0800 2014,Sat Jul 14 00:00:00 -0700 2012,Fri Jul 13 00:00:00 -0700 2012,-1,0
67783,6ad34915d4981873b6544a5d1d3451a1,8683812,4588b28a75ce0e7dc2ad88481303fc8b,4,The Paris Wife by Paula McLain is the story of...,Sun Feb 20 13:09:02 -0800 2011,Mon Nov 03 14:25:57 -0800 2014,Sat Apr 13 00:00:00 -0700 2013,Tue Apr 09 00:00:00 -0700 2013,-2,0
88188,ea6cf8e310635db9204a6e0fc33d4889,13634296,f5d358761200e942955b83d5cbb0fd5e,5,One of the best anthologies I have read in a l...,Tue May 08 15:05:28 -0700 2012,Mon Nov 03 14:34:06 -0800 2014,Thu Jul 12 00:00:00 -0700 2012,Tue May 08 00:00:00 -0700 2012,-1,0
98839,66e37e7161a5ea6c915700bb0eba8ef2,13634296,534bc58caf4eea2fe861bea92309918c,5,Not biased as my story is one of those within ...,Fri May 04 16:31:38 -0700 2012,Mon Nov 03 14:33:55 -0800 2014,Mon Jul 02 08:09:54 -0700 2012,Fri May 04 00:00:00 -0700 2012,-1,2
108070,81c93420876eac8c92478944d63ea4b0,9871944,b3b454fa41fb31d465b337bc73551ab1,4,"""Secrets and lies! It's all secrets and lies!""...",Mon Nov 14 14:12:08 -0800 2011,Mon Nov 03 14:29:02 -0800 2014,Sun Oct 14 03:03:10 -0700 2012,Sat Oct 13 00:00:00 -0700 2012,-1,15

In [31]:
reviews.loc[reviews['review_id']=='be50b7406fcff1770b983f53ce55aa37']['review_text']

86516    "I cheated on her every day. In my mind, I tho...
Name: review_text, dtype: object

In [32]:
reviews.iloc[86516]['review_text']

'"I cheated on her every day. In my mind, I thought of you in ways I shouldn\'t have, again and again. She was nothing compared to you. I\'ve never felt this way about anybody before--" \n What\'s the saying? Once a cheater, always a cheater? Oh, the fucking hypocrisy. \n There were many things I wanted to do to Anna Oliphant throughout this book. Some of them involve a bottle of choloroform, a shovel, and an unmarked grave. Mostly, I just want to bring Anna in front of the US Congress as an example of how the US educational system has grievously failed our students. To be frank, Anna Oliphant is a motherfucking idiot. \n Yeah, I guess you could say this is a sweet romance, but it\'s not the good sort of sweet. It\'s the "Oh my god, why did I eat that entire package of Oreos? I DON\'T EVEN LIKE OREOS!" sort of sweet. It\'s sickening, and best in small doses, and I still feel like I need an internal cleanse after spreading the reading of this book over several days. The good thing about it is that this book isn\'t the sugar-free type of sweet, so there were no anal explosions. It wasn\'t the worst contemporary I\'ve ever read, but this book was tremendously annoying and I simply do not understand the hype. I know many of people enjoyed it, and I can see why. Anna is the sort of character that grows on you, much like mildew, or herpes. Once you get used to having it, it doesn\'t really bother you much anymore. \n I\'m not opposed to romance. I love romance, but I read this book hoping to be swept away by a romance. Instead, I was sucked into a whirlwind of idiocy. \n Oh, the Stupidity!!: \n The only French word I know is oui, which means "yes," and only recently did I learn it\'s spelled o-u-i and not w-e-e. \n People like Anna Oliphant is the reason why everyone hates Americans. Anna is 17, and she is a moron. She is the epitome of the stupid, ignorant, egocentric American. For fuck\'s sakes, she thinks there are motherfucking mimes on every fucking corner in France. She thinks that people go watch mimes as an everyday pastime! \n I\'m going to be sick. I\'m going to vomit that weird eggplant tapenade I had for dinner, and everyone wil hear, and no one will invite me to watch the mimes escape from their invisible boxes, or whatever it is people do here in their spare time. \n I\'m sorry, but I\'m inclined to judge anyone who doesn\'t know that \n oui \n is spelled o-u-i and not w-e-e. It\'s one of those foreign words that isn\'t even fucking foreign because it\'s so fucking common. Oui is yes in French. Si is yes in Spanish. It\'s one of those words that\'s so fucking commonly used that you have to be a complete birdbrain not to know! \n Anna is terrified of anything foreign, although to me, France really isn\'t that foreign or exotic, but I didn\'t grow up in Atlanta. Is Atlanta really that ass-fucking backward? Is Atlanta really completely isolated from the rest of the world, despite being one of the biggest cities in the US (Anna\'s words). Do they not have paninis in Atlanta? \n "Where have you been all my life?" I ask the beautiful panini. "How is it possible I\'ve never had a sandwich like this before?" \n Not only is she ignorant, she has no survival skills. Anna is in Paris, attending a school for Americans. Fucking everyone speaks English, the French teachers speak English. Anna is terrified of getting food in the cafeteria and avoids the cafeteria for weeks because she doesn\'t know how to order food. \n Let me tell you a brilliant way of ordering food, in any language. You smile, you make eye contact at the desired food, you point, you nod. It\'s motherfucking universal. \n I hate to say it, but if you\'re a pretty girl, you can get anyone\'s help (most likely a guy, but often another girl, too) just by looking cute and helpless and tilting your head at an angle (guilty as charged). It ain\'t feminist, but it works when one is desperate, and the fact that Anna doesn\'t have the fucking common sense to do this instead of hiding in her room for weeks like a motherfucking pussy doesn\'t bring her up in my estimation. I\'m not judging Anna for being shy. Anna is not shy. I was a shy, shy teenager. Anna is incompetent. There is a difference between incompetency and shyness. \n After weeks and weeks of going to classes, of learning French...Anna doesn\'t know how to fucking spell "please" in French. \n Mer is next in line, and I transcribe her speech phonetically. \n Oon ploss see voo play. \n That\'s suppsed to be une place, s\'il vous plait. \n Her impression of Paris is one with like, blah blah Marie Antoinette and that really short dude, like, I think his name is Napoleon? You know, like, the one on the horse in that painting by that dude? And oh my god, the Moulin Rouge, and that cute little movie with the little girl in the yellow thingy! Madeline! \n And this is a chick who wants to be a film critic when she grows up. \n My dream is to study film theory in California. I want to be our nation\'s greatest female film critic. \n Although judging from the way she thinks, I think she\'s more suited to a career writing for the tabloids, the type with the sort of "PRESIDENT OBAMA CAUGHT IN INTERPLANETARY ORGY ALONG WITH PUTIN AND MERKEL" headline rather than as a film critic. \n I wonder if Matt is a better kisser now that he has someone more experienced to practice on. He was probably a bad kisser because of me. \n Oh, no. \n I\'m a bad kisser. I am, I must be. \n Someday I\'ll be awarded a statue shaped like a pair of lips, and it\'ll be engraved with the words WORLD\'S WORST KISSER.And Matt will give a speech about how he only dated me because he was desperate, but I didn\'t put out, so I was a waste of time because Cherrie Milliken liked him all along and she totally puts out. \n Oh God. Does Toph think I\'m a bad kisser? \n Anna, Anna, ANNA!!!!!: So beautiful without knowing it!! So perfect! So adorably fucking clumsy! She even looks gorgeous when she falls flat on her fucking face! \n "You\'re beautiful." \n I trip and fall down on the sidewalk. \n I look away as he takes my hand and helps me up. "I\'m fine. Fine!" I say, brushing the grit from my palms. Oh my God, I AM a freak. \n "You\'ve seen the way men look at you, right?" he continues. \n "If they\'re looking, it\'s because I keep making a fool of myself." \n I\'ve seen this before. And it ain\'t cute. Spare me the whole adorkable thing. I don\'t like Zooey Deschanel, and I don\'t like Anna. It just looks like she\'s trying too fucking hard, and the cute but oh-so-clumsy trope is just so fucking overplayed right now. I wash my hands of it. \n It\'s not blatant, but the relationships between the girls in this book are meant to portray Anna as the good one, the best one, the most adorakablest girly girl in the whole wide fucking world. Rashmi is "Rash." Cute. I don\'t think so. Mer is just a little chubby. Volleyball player chubby, but it\'s ok ^_^; Amanda the slut, Amanda the bitch. And Anna. Anna is just so good because you know, she feels really bad that Etienne likes her, so she does everything she can to make Mer not jealous. It\'s not Mer\'s fault that she\'s not good enough for Etienne! And boy, Saint Anna keeps reminding us that she\'s a good person! \n And poor Ellie. Poor Ellie, Etienne\'s girlfriend. But surely, it\'s ok for Etienne to cheat on Ellie with Anna if she looks like a slut, right? \n Slutty nurse. I don\'t believe it. Tiny white button-up dress, red crosses across the nipples. Cleavage city. \n CHEATING IS OK IF YOUR GIRLFRIEND IS A BITCH: That\'s the message that this book sends. Oh, that Ellie. That stupid, stuck up Ellie. Ellie who thinks she is better than everyone else. Surely it\'s fine if Etienne seeks comfort elsewhere if his girlfriend is a cold fish, a stuck up snot, right? No. I don\'t fucking think so. How about you break up with her FIRST? Just because a girl is a jerk doesn\'t mean she deserves to be cheated on. I do not appreciate the way this book sends the message that it\'s morally acceptable to cheat on a girlfriend who neglects you! But it\'s morally acceptable to cheat on her if you feeeeeeeeeeeeel bad about it, right? Fuck this shit. \n THE CHEATING: And yes, it is cheating. What do you call this? \n "I said you were beautiful. I slept in your bed!" \n "You never made a move! You had a girlfriend!" \n "No matter what a terrible boyfriend I was, I wouldn\'t actually cheat on her. But I thought you\'d know. With me being there, I thought you\'d know." \n Ok. Etienne has a girlfriend, Ellie. Etienne holds hands with Anna. He is still with Ellie. \n It\'s nice holding hands. Comfortable. \n I wish friends held hands more often, like the children I see on the streets sometimes. I\'m not sure why we have to grow up and get embarrassed about it. \n You know why? Because you wouldn\'t like it if Etienne held hands with another girl if he was dating YOU. Fucking hypocrite. \n Friends don\'t sleep in each others\' beds. \n I mean I didn\'t SLEEP sleep with him. Obviously. But I slept with him. \n I slept with a boy! I burrow back down into my sheets and grin. \n And that boy has a girlfriend. And then you do it again. While he still has a girlfriend. While you have an almost-boyfriend. \n You make eye contact and blush at each other in a theatre. While he has a girlfriend. \n You kiss each other. While he has a girlfriend. While you have an almost-boyfriend. \n You flirt with each other. While he has a girlfriend. While you have an almost-boyfriend. \n I don\'t see this relationship lasting very long.'

In [ ]:
reviews_light = reviews.copy().drop(columns=)

In [7]:
from my_shelves.utils.dataset import get_books, get_reviews

get_books(data_dir='../data').head()

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,...,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
0,NaN,7,['189911'],US,eng,"[{'count': '58', 'name': 'to-read'}, {'count':...",B00071IKUY,False,4.03,NaN,...,NaN,Book Club Edition,1987.0,https://www.goodreads.com/book/show/7327624-th...,https://images.gr-assets.com/books/1304100136m...,7327624,140,8948723,"The Unschooled Wizard (Sun Wolf and Starhawk, ...","The Unschooled Wizard (Sun Wolf and Starhawk, ..."
1,0743294297,3282,[],US,eng,"[{'count': '7615', 'name': 'to-read'}, {'count...",NaN,False,3.49,B002ENBLOK,...,7.0,NaN,2009.0,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,6066819,51184,6243154,Best Friends Forever,Best Friends Forever
2,NaN,60,['1052227'],US,eng,"[{'count': '54', 'name': 'currently-reading'},...",B01NCIKAQX,True,4.33,B01NCIKAQX,...,NaN,NaN,NaN,https://www.goodreads.com/book/show/33394837-t...,https://images.gr-assets.com/books/1493114742m...,33394837,269,54143148,The House of Memory (Pluto's Snitch #2),The House of Memory (Pluto's Snitch #2)
3,555118000X,19,[],US,eng,"[{'count': '3488', 'name': 'to-read'}, {'count...",NaN,False,3.82,NaN,...,NaN,NaN,NaN,https://www.goodreads.com/book/show/89373.The_...,https://s.gr-assets.com/assets/nophoto/book/11...,89373,77,1080201,The Bonfire of the Vanities,The Bonfire of the Vanities
4,0842379428,566,[],US,eng,"[{'count': '6393', 'name': 'to-read'}, {'count...",NaN,False,4.26,B000FCKCJC,...,NaN,NaN,NaN,https://www.goodreads.com/book/show/89376.Heaven,https://images.gr-assets.com/books/1406508230m...,89376,7345,86257,Heaven,Heaven

In [ ]:
import my_shelves
my_shelves.__file__